### ISSUE TITLE
JanusGraph Consuming too much memory

### ISSUE THREAD

**Issue by akshayB1993** [JanusGraph/janusgraph#1022]
I just started JanusGraph and my total RAM usage is more than 5GB without firing any queries. I have the following dependent services running

1. JanusGraph
2. GremlinServer (via JanusGraph)
3. Cassandra (via JanusGraph)
4. Elasticsearch (via JanusGraph)

![image](https://user-images.githubusercontent.com/22520606/39046603-5bcec438-44b4-11e8-910a-bd552e2e112e.png)

I am trying to find out the minimum system requirements for janusgraph but I am unable to find it mentioned in its documentation. Does anyone have a link for the same? or any idea how much is the minimum system requirements?

Also are there any configuration changes to make it consume less RAM?

**Comment by robertdale** [comment]
The minimum requirements would be the sum of the aggregate of minimum requirements of each underlying component. In addition to that, you have to consider the requirements for your data set and queries.
You can tune the JVM memory for each component and JanusGraph.
JanusGraph also has its own cache settings - http://docs.janusgraph.org/latest/config-ref.html#_cache

**Comment by Visgean** [comment]
I managed to configure it to use about ~300mb overall (running gremlin server). Its a bit of mess to go through the structure of the configs but you should edit files casandra-env.sh and disable caching in janusgraph-cassandra-es-server.properties

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
