### ISSUE TITLE
Add support for Google Bigtable over the Hbase interface

### ISSUE THREAD

**Issue by lindsayismith** [JanusGraph/janusgraph#103]
JanusGraph should support using Google Bigtable as a backend over the HBase interface. Some minor changes are required, plus some library dependencies.

**Comment by amcp** [comment]
I vaguely remember some work you did in graphdb-benchmarks. This effectively mostly requires a configuration file, right?

**Comment by mbrukman** [comment]
I think this required some updates to the HBase backend, because it was using older APIs rather than the new HBase 1.0+ APIs, but some of the updates that @lindsayismith needed to make happened as a result of [adding support for HBase 1.2](https://github.com/JanusGraph/janusgraph/pull/94#pullrequestreview-21226333).

@lindsayismith, are there any other outstanding patches to the HBase backend to make it compatible with the Bigtable client library?

**Comment by lindsayismith** [comment]
I do have another PR I need to finish, it's quite small.  I'm working on that this week.

**Comment by jerryjch** [comment]
Closing this Issue since the PR has been merged.
