### ISSUE TITLE
Composite Index representation with Cassandra

### ISSUE THREAD

**Issue by havenwang** [JanusGraph/janusgraph#1057]
Hello, this is a 2 part question.

The first question is about how the JanusGraph composite index is implemented to work with a Cassandra backend. This is an assumption I made, but was unable to find explicitly confirmed online. Is the composite index with JanusGraph, when using Cassandra as the backend storage, directly using the Cassandra index keys? In other words, if I have a vertex with a property `_id` which I created an index for, then on Cassandra we would have something like an index column for a column corresponding to the `_id` value?

My follow up question is about performance and scalability of this graph index. From the Cassandra documentation it is stated that: "A general rule of thumb is to index a column with low cardinality of few values." Are there any concerns I should consider if creating a graph index like `_id` for ID values, and so having a high cardinality? Or does the JanusGraph index work a different way so that high cardinality is not as much an issue?

**Comment by twilmes** [comment]
The composite index is stored as an inverted index in Cassandra, mapping indexed values to a list of matching vertices. For Janus composite indexes, cardinality isn't so much of an issue as selectivity is. An index on `id` is super selective, resolving to one vertex so the Cassandra partitions in your inverted index will be incredibly "skinny" which is a good thing. An example of a property that is usually bad to use a composite index on would be a boolean property or something with say, two values like male/female. In this case, the index isn't very selective at all and you'll likely end up with Cassandra partitions that are too wide which will cause performance and operational issues.

In the future, questions like this are best handled on the [mailing list](https://groups.google.com/forum/#!forum/janusgraph-users) so that they get more visibility and others can chime in.
