### ISSUE TITLE
Storing a Map in Janusgraph

### ISSUE THREAD

**Issue by Lakedaemon** [JanusGraph/janusgraph#1064]
Is there a compact/efficient way to store a Map in janusgraph ?

It might be possible to store a map in a Vertex, by setting each map key as a vertexproperties key and the corresponding value as the corresponding vertexProperty value, 
but it would only be possible with schemaless janusgraph, right ?

It might be possible to store a map as a graph with vertexes as keys and vertexPropertu as value, but isn't this completely inneficient (beside, you have to index that to get decent retrieval time)

Is there a better way to store a map in a janusGraph (or should I implement MAP type support ?)

Storing a Set of values that can have properties would be nice too, is it possible ?

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
