### ISSUE TITLE
Why the first gremlin request excution consume long time

### ISSUE THREAD

**Issue by myitroad** [JanusGraph/janusgraph#1071]
Hi,
In our development, we get and cached GraphTraversalSource with
`g = EmptyGraph.instance().traversal().withRemote(DriverRemoteConnection.using(cluster));`

When we post the first gremlin request, the excution will consume long time.  But the later gremlin request will be excuted obviously faster.
So, how to faster the first request after the application started?

In the JanusGraph server, we adopt the [JanusGraph Server as a WebSocket Endpoint](http://docs.janusgraph.org/0.1.0/server.html#_janusgraph_server_as_a_websocket_endpoint).

**Comment by twilmes** [comment]
When you say the first request is slow, how long does it actually take? A few seconds, a minute? Is that the first request after the Gremlin server has been restarted? If so, I'd expect it to need to "warm up". For one, the JVM may be jitting code. If your request has a mutation in it, Janus may be grabbing an initial block of ids which can be slow. If you are concerned about startup time I'd recommend profiling the application to see where the slow down is.

**Comment by myitroad** [comment]
Sure, it happens after the Gremlin server or our application has been restarted.

We haven't measure how long it will be taken for the first request,,because different traversal step consume different time. Feeling it seems at least twice longer than the later request.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
