### ISSUE TITLE
[Question] Backend operation thread pool - what is the impact on the performance

### ISSUE THREAD

**Issue by mikebocian** [JanusGraph/janusgraph#1088]
Hi there, 

I've got a question for you guys. We are using Janusgraph with 3-nodes BigTable cluster as a backend. We don't have a separate Gremlin server - each of our instances have Janusgraph embedded inside the JVM. 

So, we are currently importing big set of data ( something around 1TB let's say ). This graph is quite dense so we decided to use many small transactions ( which modify only a small part of the graph, let say ~100 vertices, up to 2kB in total ). Currently we have importing "speed" something around 300 of this small transactions / s.

From your experience, how to make this import quicker? What impact the connection pool to BigTable have for performance in such situations. Taking into an account, that this ThreadPool cannot be changed from client code: ```Initiated backend operations thread pool of size``` we decided to go with many small replicas of our system ( only to increase this thread pool size, somehow artificially ). But still, I think we can go faster. 

BigTable says, that we are reading & writing something around 3k rows/s ( sometimes reads are ~ 10k ). Probably it could go faster, when we finally finish our import. 

I will be glad if you guys decide to share with your experience regarding performance issues.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
