### ISSUE TITLE
Individual key range is too small for partition block

### ISSUE THREAD

**Issue by huxiaoqing0704** [JanusGraph/janusgraph#1145]
When I open graph
_graph = JanusGraphFactory.open('conf/gremlin-server/warehouse-janusgraph-datasource.properties')_
There are many warns like the followings,
![image](https://user-images.githubusercontent.com/15335756/42319252-fc608f20-8083-11e8-8167-2372b1469c10.png)
I do not know what happens. Also I don't know how these warnings affect queries. 
Does anyone else have a similar problem?
The following is the configuration file.
 
![image](https://user-images.githubusercontent.com/15335756/42319674-455886c8-8085-11e8-84d9-007317ce56af.png)

**Comment by pluradj** [comment]
`ids.block-size` value of 30 million seems excessively large to me. The exception message "Individual key range is too small for partition block" sounds like the space for storing IDs has run out.

As described in the [docs](https://docs.janusgraph.org/latest/config-ref.html#_ids):
 
> Globally reserve graph element IDs in chunks of this size. Setting this too low will make commits frequently block on slow reservation requests. Setting it too high will result in IDs wasted when a graph instance shuts down with reserved but mostly-unused blocks.

**Comment by huxiaoqing0704** [comment]
_ids.block-size_  is related to  memory?

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
