### ISSUE TITLE
Refactor GraphDatabaseConfiguration and improve test coverage

### ISSUE THREAD

**Issue by chupman** [JanusGraph/janusgraph#1148]
It's currently very difficult to test [GraphDatabaseConfiguration Class](https://github.com/chupman/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java#L1235)

Once it's refactored the upgrade feature from PR #998 needs test coverage.

**Comment by chupman** [comment]
Once it's refactored it should also be possible to test [checkBackwardCompatibilityWithTitan](https://codecov.io/gh/JanusGraph/janusgraph/src/storage-version/janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java#L1449)

**Comment by porunov** [comment]
@chupman I've refactored and covered the main logic of old `GraphDatabaseConfiguration` with unit tests. Further refactoring and coverage with tests requires to refactor other parts of the code which use `GraphDatabaseConfiguration`. So, I think this issue is resolved. I think for further refactoring and testing we should use new issues which are more specific.
What do you think? Can we close this issue or you think we should target some other PRs to this issue?

**Comment by chupman** [comment]
@porunov you went well above and beyond what I had in mind for this issue. This Can definitely be closed out. 

Thanks for taking the time to make these improvements to the codebase.
