### ISSUE TITLE
Janusgraph Direct Index Query gives unwanted message

### ISSUE THREAD

**Issue by pra527vin** [JanusGraph/janusgraph#1183]
I used direct index query to get data from Mix Index (Solr) using following query

val SERVER_CONFIG_FILE = "resources/janusgraph-cassandra-solr.properties"

  val graph: JanusGraph = JanusGraphFactory.open(SERVER_CONFIG_FILE)

  val vertexList = graph.indexQuery("DocumentIndex", "v.content:(content english)") .vertexStream()
    .iterator() .asScala .toList

the query is executed properly but whwn the jar is built 
Received:1
Received:2 
Received:3 
.
.
.
is printed in console
I am using same Janusgraph Instace for this query type
What is causing this?and how to remove this message?

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
