### ISSUE TITLE
Query Optimizer - reduce properties loaded during traversal

### ISSUE THREAD

**Issue by ewmah** [JanusGraph/janusgraph#1184]
Traceability queries result in complex multilevel traversals (joins)
Each traversal stage loads all properties of each vertex encountered

Can the query optimizer load only properties that are needed?
–Understand the ‘has’ conditions that are tested
•Load only properties in has conditions, and 
–Don’t load properties into the vertex if the composite indices end up being used
–If you are at the last level of the traversal, skip loading the full properties and only load properties returned as part of the result

**Comment by twilmes** [comment]
Thanks for the issue @ewmah. You can get around some of this by turning `query.fast-property` off, but I think there are other optimizations to made along the lines of what you're proposing.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
