### ISSUE TITLE
Unable to start gremlin server with berkeleyje server yaml in 0.3.0 RC

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#1203]
```sh
bin/gremlin-server.sh conf/gremlin-server/gremlin-server-berkeleyje.yaml
```

produces the following output:

```
Graph [graph] configured at [conf/gremlin-server/janusgraph-berkeleyje-server.properties] could not be instantiated and will not be available in Gremlin Server. GraphFactory message: GraphFactory could not instantiate this Graph implementation [class org.janusgraph.core.JanusGraphFactory]
...
caused by Caused by: java.net.UnknownHostException: elasticsearch
```

**Comment by porunov** [comment]
@amcp @pluradj This issue is sitting here for half a year and the commit in #1204 wasn't signed still.
Can a new contributor republish the same changes (i.e. the code which is written by @amcp ) with a signed commit for a new contributor behalf?

@amcp are you OK that your code will be merged from another contributor behalf? Can you sign your commit anytime soon?
