### ISSUE TITLE
lost elasticsearch data 

### ISSUE THREAD

**Issue by jxping** [JanusGraph/janusgraph#1210]
https://groups.google.com/forum/#!topic/janusgraph-users/RE6h7Kmc1OM
I have post this question
major stack is 
```
Caused by: java.lang.RuntimeException: error while performing request
	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:681)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.performRequest(RestElasticSearchClient.java:320)
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.bulkRequest(RestElasticSearchClient.java:249)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:601)
```

here is the source code 
https://github.com/JanusGraph/janusgraph/blob/v0.2.0/janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java#L226-L261

    @Override
    public void bulkRequest(List<ElasticSearchMutation> requests, String ingestPipeline) throws IOException {
        final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        for (final ElasticSearchMutation request : requests) {
            Map actionData = ImmutableMap.of(request.getRequestType().name().toLowerCase(),
                    ImmutableMap.of("_index", request.getIndex(), "_type", request.getType(), "_id", request.getId()));
                outputStream.write(mapWriter.writeValueAsBytes(actionData));
            outputStream.write("\n".getBytes(UTF8_CHARSET));
            if (request.getSource() != null) {
                outputStream.write(mapWriter.writeValueAsBytes(request.getSource()));
                outputStream.write("\n".getBytes(UTF8_CHARSET));
            }
        }

        final StringBuilder builder = new StringBuilder();
        if (ingestPipeline != null) {
            APPEND_OP.apply(builder).append("pipeline=").append(ingestPipeline);
        }
        if (bulkRefresh != null && !bulkRefresh.toLowerCase().equals("false")) {
            APPEND_OP.apply(builder).append("refresh=").append(bulkRefresh);
        }
        builder.insert(0, "/_bulk");

        final Response response = performRequest(REQUEST_TYPE_POST, builder.toString(), outputStream.toByteArray());
        try (final InputStream inputStream = response.getEntity().getContent()) {
            final RestBulkResponse bulkResponse = mapper.readValue(inputStream, RestBulkResponse.class);
            final List<Object> errors = bulkResponse.getItems().stream()
                .flatMap(item -> item.values().stream())
                .filter(item -> item.getError() != null && item.getStatus() != 404)
                .map(RestBulkItemResponse::getError).collect(Collectors.toList());
            if (!errors.isEmpty()) {
                errors.forEach(error -> log.error("Failed to execute ES query: {}", error));
                throw new IOException("Failure(s) in Elasicsearch bulk request: " + errors);
            }
        }
    }

 I think 

  ```
final Response response = performRequest(REQUEST_TYPE_POST, builder.toString(), outputStream.toByteArray());
```

should be in a try/catch.
It seems janunsgraph does not handle data losing in the code.

**Comment by pluradj** [comment]
The error is actually coming from this call to the RestClient `delegate`:

https://github.com/JanusGraph/janusgraph/blob/v0.2.0/janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java#L318-L330


    private Response performRequest(String method, String path, byte[] requestData) throws IOException {
        final HttpEntity entity = requestData != null ? new ByteArrayEntity(requestData, ContentType.APPLICATION_JSON) : null;
        final Response response = delegate.performRequest(
            method,
            path,
            Collections.<String, String>emptyMap(),
            entity);

        if (response.getStatusLine().getStatusCode() >= 400) {
            throw new IOException("Error executing request: " + response.getStatusLine().getReasonPhrase());
        }
        return response;
    }

org.elasticsearch.client.RestClient [`performRequest()`](https://artifacts.elastic.co/javadoc/org/elasticsearch/client/elasticsearch-rest-client/6.3.2/org/elasticsearch/client/RestClient.html#performRequest-java.lang.String-java.lang.String-org.apache.http.Header...-) method declares
- java.io.IOException
- org.apache.http.client.ClientProtocolException (extends IOException)
- org.elasticsearch.client.ResponseException (extends IOException)

I think the JanusGraph block above is handling this correctly because the method throws IOException. In Java you don't commonly use try/catch for RuntimeExceptions.

When you get that stack trace it means that ES was not updated. The data should still be in the storage backend. You could run a [reindex](https://docs.janusgraph.org/latest/index-admin.html#reindex) operation to get ES populated with the data.
