### ISSUE TITLE
Exclude log4j.properties in pom.xml

### ISSUE THREAD

**Issue by huynhtk** [JanusGraph/janusgraph#1236]
The janusgraph-core-0.3.0.jar includes log4j.properties which is overriding the existing application's log4j.properties file.

**Comment by pluradj** [comment]
It appears that the `log4j.properties` has been packaged in janusgraph-core.jar going all the way back to titan-core.jar. It is probably safe to remove from the jar file.

@huynhtk According to the log4j docs on the [default initialization procedure](https://logging.apache.org/log4j/1.2/manual.html#Default_Initialization_Procedure), the preferred way to specify the default initialization file is through the `log4j.configuration` system property. For example, the Gremlin Console uses this flag `-Dlog4j.configuration=conf/log4j-console.properties` to pull in the properties from the local config file rather than from the jar file.

**Comment by TotalForgot** [comment]
Dear,

It also appears in janusgraph-core-0.3.1.jar
I totally agree that it would be better to remove from the jar file.

Best
TotalForgot

**Comment by DatPhanTien** [comment]
Dear 

It is also included in janusgraph-0.4.0.jar

And it is crazy that our java projects after declaring dependency on JanusGraph cannot logout properly without overriding another log4j.properties file.

We believe that this file should be removed from the jar, and one will need to provide in extra the proper log4j.properties as his/her expectation when starting the application.

Including this file in jar brings abnormal behaviors, and this is an anti-pattern.

Best
Tien Dat
