### ISSUE TITLE
What is the usage of KCVSCache?

### ISSUE THREAD

**Issue by RaulGuo** [JanusGraph/janusgraph#1244]
I am trying to understand the source code, but I came to trouble understanding the KCVSCache, as for my understanding, the KCVSCache has only one usful method: mutateEntries.
`public void mutateEntries(StaticBuffer key, List<Entry> additions, List<Entry> deletions, StoreTransaction txh) throws BackendException {
        assert txh instanceof CacheTransaction;
        ((CacheTransaction) txh).mutate(this, key, additions, deletions);
    }
`
But I am sure it has many other usage I still don't know yet. What is the design purpose of this class and its parent KCVSProxy? There is little comment of them. Can someone help me to understand the the class and its design? thanks in advance.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
