### ISSUE TITLE
How to import large data to JanusGraph ?

### ISSUE THREAD

**Issue by zhaochl** [JanusGraph/janusgraph#1245]
I have 3.2 billions Edges and 0.3 billions Vertex To import to JanusGraph ,But it's too slow
How can speed up the import process ? can I use map-reduce or else technique ?

**Comment by shah-antriksh** [comment]
What is your current bulk load approach? Also when you say too slow, what is the speed you are getting?

One approach for bulk upload is to distribute your data using spark and upload smaller partitions into your storage backend using JG libraries. You can take a look at this link https://groups.google.com/forum/#!searchin/janusgraph-users/Bulk$20upload$20through$20janusgraph/janusgraph-users/KQOtZcm1bcw/k2itt-NxCgAJ

**Comment by dengziming** [comment]
would this help you?
https://github.com/dengziming/janusgraph-util

**Comment by dengziming** [comment]
environment:3 machines of cassandra(56vcore, 256G memory), 
data:1 billion vertices, 10 billion edges, 
cost: 9 hours

**Comment by zhaochl** [comment]
Cool ! You can write this on the README.md  of Your project

I will try it sometime , But My backend is Hbase ,and memory is much smaller

**Comment by dengziming** [comment]
@zhaochl  Hbase is not support now, because it's difficult to generate and merge HFile .you can use cassandra first.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
