### ISSUE TITLE
what is janusgraph-hbase-core dependency ?

### ISSUE THREAD

**Issue by zhaochl** [JanusGraph/janusgraph#1255]
```
<dependency>
    <groupId>org.janusgraph</groupId>
    <artifactId>janusgraph-hbase</artifactId>
    <version>0.1.0</version>
</dependency>
```                              

dependency:

```
 <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>janusgraph-hbase-core</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>janusgraph-hbase-098</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>janusgraph-hbase-10</artifactId>
            <version>${project.version}</version>
            <optional>true</optional>
        </dependency>
    </dependencies>
```

but I can not find `janusgraph-hbase-core`  anywhere ?

**Comment by pluradj** [comment]
It is not clear what you are trying to accomplish. `janusgraph-hbase-core` does not produce a jar file, so you should not list it as a dependency for your application. `janusgraph-hbase` should be used because it includes the `janusgraph-hbase-core` classes from the [source directory](https://github.com/JanusGraph/janusgraph/tree/v0.1.0/janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java).

You should consider using a more recent version of JanusGraph. 0.3.0 is the latest.

@zhaochl — please use GitHub only to report specific bugs or feature requests.

For general questions or open-ended discussion, please use either the Gitter channel or the `janusgraph-users@` mailing list: https://github.com/janusgraph/janusgraph/#community .

**Comment by aleclerc** [comment]
According to https://mvnrepository.com/artifact/org.janusgraph/janusgraph-hadoop-core/0.3.0 `janusgraph-hbase-core` is a compile dependency of `janusgraph-hadoop-core`. So if you import janusgraph-hadoopcore:
```
		<dependency>
	    <groupId>org.janusgraph</groupId>
	    <artifactId>janusgraph-hadoop-core</artifactId>
	    <version>0.3.0</version>
		</dependency>
```
then it fails to resolve `janusgraph-hbase-core` since it's unavailable.
