### ISSUE TITLE
how to resolve elasticsearch property value version conflict?

### ISSUE THREAD

**Issue by vipsql** [JanusGraph/janusgraph#1270]
[ERROR 2018-09-22 21:58:19 o.j.d.e.r.RestElasticSearchClient:271 TripleWriteBolt:13-Executors] Failed to execute ES query: {type=version_conflict_engine_exception, reason=[PERSON_NAME][1erzxs]: version conflict, current version [435] is different than the one provided [434], index_uuid=JlzS9DkmSTu-KYFPeVgwmQ, shard=4, index=graph_index_person_name}

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
