### ISSUE TITLE
Vertex does not support user supplied identifiers

### ISSUE THREAD

**Issue by taherchhabra** [JanusGraph/janusgraph#1274]
When I try to run this query
`g.addV('user').property(id,'6579093871008872-1535760432')`

I get `Vertex does not support user supplied identifiers` error

I have added `graph.set-vertex-id=true`  in the `conf/gremlin-server/janusgraph-cassandra-es-server.properties` config file

Is this above config option correct to enable user supplied ids and have I made the change in the correct config file ? I am confused since there are so many config files 

I am using the Pre-Packaged Distribution from [this](https://docs.janusgraph.org/latest/server.html) page

thanks for the help

**Comment by czheo** [comment]
1. Once you add `graph.set-vertex-id=true`, make sure you don't see warning like below.
~~~
WARN  org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration  - Local setting graph.set-vertex-id=true (Type: FIXED) is overridden by globally managed value (false).  Use the ManagementSystem interface instead of the local configuration to control this setting.
~~~
If you see such warning, you may need to drop the database first.

2. Once you make sure `set-vertex-id` is set to true, you may run the query as below
~~~
g.addV('user').property(id, graph.getIDManager().toVertexId(123))
~~~
where `123` is user provided id.
AFAIK, string type id is not supported yet. https://github.com/JanusGraph/janusgraph/issues/1221

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.

**Comment by Tin-Nguyen** [comment]
@czheo @taherchhabra , 

I get the same error message when I'm trying to run the query below via [JanusGraph docker container](https://hub.docker.com/r/janusgraph/janusgraph)
```
g.addV('person').property(id, graph.getIDManager().toVertexId(123))
```
I did try to drop the database (even killed the container and its data and re-inited new one) and make the setting `graph.set-vertex-id=true`, however it keeps showing the warn logging
```
WARN  org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration  - Local setting graph.set-vertex-id=true (Type: FIXED) is overridden by globally managed value (false).  Use the ManagementSystem interface instead of the local configuration to control this setting.
```
I don't know how exactly do delete the database to resolve this issue or if we have any other way please let me know. Thanks!

**Comment by eEQK** [comment]
If you're using microsoft's gremlin plugin for spring data, you may find this helpful: https://groups.google.com/g/janusgraph-users/c/XCg1gVYPmE4
