### ISSUE TITLE
Questions about Vertex-centric Indexes

### ISSUE THREAD

**Issue by huxiaoqing0704** [JanusGraph/janusgraph#1283]
I see the following description in the chapter **11.2. Vertex-centric Indexes**.
![image](https://user-images.githubusercontent.com/15335756/46520359-49092180-c8ae-11e8-8ae2-9f268ec46d43.png)
Does this mean that I don't need to create the  vertex-centric indexes myself when using JanusGraph to do development?

**Comment by porunov** [comment]
@huxiaoqing0704 you should ask questions on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users). GitHub issues only for bugs and feature requests.
You are right, you shouldn't create vertex-centric indexes yourself for **edge labels** and **property keys of the vertex**. In case you want to use indexes for edge properties then you should create such vertex-centric indexes by yourself. For example, if you have `friend` edges with a property `since` and you would like to return top 10 oldest friends (`g.V(h).outE('friend').order().by('since').inV().limit(10)`) then you should create such vertex-centric index yourself (`mgmt.buildEdgeIndex(friendEdge, 'friendsByTime', Direction.BOTH, Order.decr, sinceProperty)`).

**Comment by jxping** [comment]
a vertex centric index means make a new edge accroding to your schema, edge between node and schema so you can san hbase with filters to speed up your query

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
