### ISSUE TITLE
Query through edge doesn't  use Mixed index.

### ISSUE THREAD

**Issue by huxiaoqing0704** [JanusGraph/janusgraph#1310]
I have a query like this , as followings:

`g.V(77668600).bothE("data.link.unit_member_rel").as("e").otherV().has("person_base_info.name",textContains("石")).as("v").path().as("p").select("e", "v", "p").by(valueMap(true)).by(valueMap(true)).by().profile()`

The Vertex[77668600] has almost 10000 link persons. Execute the query above is very slow Because the **_textContains_** step take about ten second.
![image](https://user-images.githubusercontent.com/15335756/47764229-35ab7380-dcff-11e8-99bc-aaed0dbc9cb6.png)

After checking the source code, **I found that this  _textContains query_ above doesn't use mixed index and execute compare in memory.(**The source code class is** **_org.janusgraph.core.attribute.Text_**)**

**Comment by huxiaoqing0704** [comment]
My janusgraph version is 0.2.0.

**Comment by TitiHl** [comment]
@huxiaoqing0704 what search backend are you using. and be aware of usage of "Text" or "String" when building the index. refers to:
https://docs.janusgraph.org/latest/index-parameters.html

**Comment by huxiaoqing0704** [comment]
@TitiHl  thanks for your reply.
 My search backend is Elasticsearch.
 I have build mixed index for _**person_base_info.name**_ property key.
If I execute the query **_g.V().has("person_base_info.name",textContains("石"))_** the mixed index work very well.
But, the query **_g.V(77668600).bothE("data.link.unit_member_rel").otherV().has("person_base_info.name",textContains("石"))_** doesn't use mixed index and is compared in the memory.(The source code class is org.janusgraph.core.attribute.Text)

**Comment by FlorianHockmann** [comment]
Graph indices (to which mixed indices belong) can only be used in the beginning of a traversal to select starting points in the graph. It is not possible to use them mid-traversal like you're trying to do here. Filtering the elements locally in-memory should also be more efficient than doing an Elasticsearch request and then filter the elements based on the results of that request because all necessary information is already available locally.
In the future, please don't use GitHub issues for general usage questions like this. Instead, you can ask on the [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) Google group or in [our Gitter chat](https://gitter.im/janusgraph/janusgraph).
