### ISSUE TITLE
drop cause OperationTimedOutException 

### ISSUE THREAD

**Issue by doofin** [JanusGraph/janusgraph#1311]
```
[ERROR] com.datastax.driver.core.exceptions.OperationTimedOutException: [/127.0.0.1:9042] Timed out waiting for server response
jvm[ERROR] 	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:44)
jvm[ERROR] 	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:26)
jvm[ERROR] 	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
jvm[ERROR] 	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
jvm [/127.0.0.1:9042] Timed out waiting for server response
jvm[ERROR] 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
jvm[ERROR] 	at org.janusgraph.diskstorage.cql.CQLStoreManager.clearStorage(CQLStoreManager.java:409)
jvm[ERROR] 	at org.janusgraph.diskstorage.Backend.clearStorage(Backend.java:588)
jvm[ERROR] 	at org.janusgraph.core.JanusGraphFactory.drop(JanusGraphFactory.java:212)

```

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
