### ISSUE TITLE
janusgraph.sh quits with no message.

### ISSUE THREAD

**Issue by EdwardJB** [JanusGraph/janusgraph#1318]
```
(scratch) ed@pop:~/Downloads/janusgraph-0.2.2-hadoop2$ bin/janusgraph.sh start
Forking Cassandra...
(scratch) ed@pop:~/Downloads/janusgraph-0.2.2-hadoop2$ bin/janusgraph.sh stop
Gremlin-Server (org.apache.tinkerpop.gremlin.server.GremlinServer) not found in the java process table
Elasticsearch (org.elasticsearch.bootstrap.Elasticsearch) not found in the java process table
Cassandra (org.apache.cassandra.service.CassandraDaemon) not found in the java process table
(scratch) ed@pop:~/Downloads/janusgraph-0.2.2-hadoop2$ 
```

`cassandra.log` is empty.

System info:

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.04 LTS
Release:	18.04
Codename:	bionic
```

**Comment by mbrukman** [comment]
@EdwardJB — this script runs in server mode, so no output is expected, unless there are any errors, but there are none in this case, which is good!

Did you want to see a Gremlin prompt? In that case, please see [getting started guide](https://docs.janusgraph.org/latest/getting-started.html) and run `bin/gremlin.sh` instead.

**Comment by FlorianHockmann** [comment]
@EdwardJB Please try it again with the verbose flag:
```bash
bin/janusgraph.sh start -v
```
That should provide more output to debug the issue.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
