### ISSUE TITLE
Setting two or more properties on existing edge

### ISSUE THREAD

**Issue by Tanvi-Bhandari** [JanusGraph/janusgraph#1329]
I have a partition vertex in my schema. and created an edge between such two vertices.
v1 --> v2 (v1 and v2 are of type partition vertex, there is an edge from v1 to v2)
in a separate transaction, if i try to set two or more properties(in single transaction) on this edge. it is creating multiple edges.
Example: v1 --> v2 : edge : e1
in another transaction I set p1 and p2 properties on e1. Once this transaction is committed and closed. 
the graph is showing two edges between v1 and v2. Out of which, one edge has p1 property and another has p2 property set on it.

I believe, the reason is following code: 
org.janusgraph.graphdb.relations.CacheEdge.update() API:
```
private synchronized InternalRelation update() {
        StandardEdge copy = new StandardEdge(super.longId(), edgeLabel(), getVertex(0), getVertex(1), ElementLifeCycle.Loaded);
        copyProperties(copy);
        copy.remove();
        StandardEdge u = (StandardEdge) tx().addEdge(getVertex(0), getVertex(1), edgeLabel());
        if (type.getConsistencyModifier()!=ConsistencyModifier.FORK) u.setId(super.longId());
        u.setPreviousID(super.longId());
        copyProperties(u);
        setId(u.longId());
        return u;
    }
```
This API first removes the existing edge and then create another edge whenever the new property is set on existing edge.

Since, both properties p1 and p2 are set in same transaction, this piece tries to create another edge from same existing edge and hence end up creating two edges.

is this behavior for edges on partition vertex expected?

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
