### ISSUE TITLE
Does janusgraph support mathematical operation sucha as addition, multiplication, division?

### ISSUE THREAD

**Issue by pra527vin** [JanusGraph/janusgraph#1338]
I have to calculate some value using janusgraph query is it possible in janusgraph
example :
I have property price in Product vertex if I have to display price with 10% discount how to write such query in janusgraph?

**Comment by porunov** [comment]
@pra527vin You should ask such questions here: https://groups.google.com/forum/#!forum/janusgraph-users . Issues are used only for bugs reports and feature requests.

Yes, all those operation are supported in additional to other math operations. Here is the mathematical step documentation: http://tinkerpop.apache.org/docs/current/reference/#math-step

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
