### ISSUE TITLE
something wrong when making Mixed Index

### ISSUE THREAD

**Issue by oushu1liwenhui1** [JanusGraph/janusgraph#1359]
hello,i tyied to create mixed index according to the  documentation, and the command is "graph.tx().rollback()  //Never create new indexes while a transaction is active
mgmt = graph.openManagement()
name = mgmt.getPropertyKey('name')
mgmt.buildIndex('byNameUnique', Vertex.class).addKey(name).unique().buildCompositeIndex()
mgmt.commit()
//Wait for the index to become available
ManagementSystem.awaitGraphIndexStatus(graph, 'byNameUnique').call()
//Reindex the existing data
mgmt = graph.openManagement()
mgmt.updateIndex(mgmt.getGraphIndex("byNameUnique"), SchemaAction.REINDEX).get()
mgmt.commit()"
but the result is "Cannot invoke method get() on null object".
please tell me why and how to make it work.
thanks and happy new year.

**Comment by FlorianHockmann** [comment]
You're getting this exception here because `updateIndex()` returns `null` as you're index is probably not in a state where `REINDEX` is an allowed action. I created #1378 to make it easier to see this problem in the future.

Please don't use GitHub issues to ask about problems. We have [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) and a [Gitter chat](https://gitter.im/janusgraph/janusgraph) for that.
