### ISSUE TITLE
how to get the VertexPropery by the vertexID,propertyName and propertyValue ?

### ISSUE THREAD

**Issue by vipsql** [JanusGraph/janusgraph#1366]
how to get the VertexPropery by the vertexID,propertyName and propertyValue ?
example: 

data:
  john -> age -> 15
 the  vertexPropery is dataVersion-> 0.0.1

querycondtion: 
   vertexID:  john
   propertyName: age
   propertyValue: 15

i want quick to get dataVersion

**Comment by porunov** [comment]
@vipsql I am not sure I get your question fully.

If `vertexID` is one of parameters and you need to get a value of `dataVersion` parameter then the query would look something like:
`g.V().has('vertexID', 'john').has('age', '15').values('dataVersion')`

If `vertexID` is the `id` of the vertex then the question is confusing. The thing is that `id` data type is `Long` in JanusGraph. So, instead of `john` you will have something like `12345`.
If you have the `id` of the vertex than you don't need other conditions apply to find a vertex. So, you can make a query like:
`g.V(vertexID).values('dataVersion')`

Also, please, don't use GitHub issues to post your questions. They are meant to be used only for bug reports and feature requests. 
You can use this group to ask your questions about JanusGraph: https://groups.google.com/forum/#!forum/janusgraph-users

Notice, that your question isn't related directly to JanusGraph but to Gremlin language. You can get answers related to Gremlin faster in this group:
https://groups.google.com/forum/#!forum/gremlin-users

**Comment by vipsql** [comment]
@porunov  thanks
