### ISSUE TITLE
Can janusgraph support the ClickHouse?

### ISSUE THREAD

**Issue by ggservice007** [JanusGraph/janusgraph#1370]
I love janusgraph and ClickHouse.

https://github.com/yandex/ClickHouse/issues/4001

We can together make it. 

So nice.

**Comment by ggservice007** [comment]
@porunov 
So nice.
I will try it.

**Comment by blinkov** [comment]
Briefly browsed around source/docs and it sounds like JanusGraph uses those backends just for read/write queries for specific keys. If that's right there's not much sense to add ClickHouse to that backends list, because it's optimized for batch writes and analytical retrieval queries (with aggregation, joins, sorts, etc.) which is completely different workload.

**Comment by ggservice007** [comment]
@porunov 

Thanks  a lot.

Maybe we can write a new store format for the ClickHouse.

**Comment by porunov** [comment]
@ggservice007 I am not familiar with ClickHouse and don't know if it is wise to use it as a storage backend. All I know is that it is a column-oriented database management system. If so, then it is possible to use it as a storage backend. But to understand if you **should** use it as a storage backend you need to dig into ClickHouse.

**Comment by blinkov** [comment]
@porunov what kind of queries are typically issued to those backends?
