### ISSUE TITLE
Intermittent empty query results for recursive query

### ISSUE THREAD

**Issue by diablofon** [JanusGraph/janusgraph#1399]
Observed on JanusGraph 0.3.1 with Cassandra as the storage backend and Solr as the index backend.

Problem is observed on both: gremlin console and my home grown application connected to Janus Graph. 
When I open gremlin console and execute e.g. following query I get empty results from time to time:
```
g.V().has('id', 'e0ee557d-9171-4f43-83c7-13e043657ad9')
  .repeat(inE().has('name', within('flow_design','flow_equivalent','flow_impact','flow_internal','flow_manual','flow_operational','flow_system','flow_viewbase')).outV().simplePath())
  .until(inE().has('name', within('flow_design','flow_equivalent','flow_impact','flow_internal','flow_manual','flow_operational','flow_system','flow_viewbase')).outV().count().is(0))
  .path().toList()
```
Then I need to exit console, open it once again and rerun query. When query returns empty result I repeat above steps, when query returns the result I'm done.
The same happens with my app, I need to restart it (close and open connection to Janus) until I get correct query results.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
