### ISSUE TITLE
Update Cassandra driver to 4.x version

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#1510]
Cassandra driver 4.0.0 is released. Possibly it requires some testing and researching before updating to `4.x` branch, but I think it will be a main branch in the long term, so I think that it is wise to update the driver to `4.x` version.

**Comment by porunov** [comment]
Example of the implementation can be seen here #1733

**Comment by smcquillan** [comment]
@porunov, wonder if you can help with this. 

We’re using JanusGraph within a Dropwizard application which has forced us to upgrade `io.dropwizard.metrics` to version 4.x. This, in turn, means when we attempt to use JanusGraph with CQL we get a ClassNotFoundException about `com.codahale.metrics.JmxReporter` which matches the  stack trace described by Datastax here:

https://docs.datastax.com/en/developer/java-driver/3.8/manual/metrics/#metrics-4-compatibility

I don’t think this would be an issue for the 4.x drivers so I took a look at the example implementation linked to above to see how easy it would be to finish it off. However, I quite quickly ran into problems with Apache Cassandra Hadoop’s [CqlInputFormat](https://github.com/apache/cassandra/blob/cassandra-3.11/src/java/org/apache/cassandra/hadoop/cql3/CqlInputFormat.java#L28) and [CqlRecordReader ]( https://github.com/apache/cassandra/blob/cassandra-3.11/src/java/org/apache/cassandra/hadoop/cql3/CqlRecordReader.java#L45) classes, both of which JanusGraph is using within the [org.janusgraph.hadoop.formats.cql](https://github.com/JanusGraph/janusgraph/tree/master/janusgraph-cql/src/main/java/org/janusgraph/hadoop/formats/cql) package from `cassandra-cql`. The problem is that even on the Cassandra 3.11 branch these classes are using older 3.x Datastax drivers and so won’t compile if I attempt to upgrade the driver used by JanusGraph to 4.x.

There is an alternative way around the problem that is described in the link above and that’s to connect using `withoutJMXReporting()`. I’ve done some successful testing in this area by making a local configuration option to allow JMX reporting to be disabled. If people think this sounds like a viable workaround in the short term, I could raise a pull request.

**Comment by farodin91** [comment]
We have to wait until Cassandra which to the new driver.

**Comment by porunov** [comment]
@smcquillan datastax cassandra driver 4 and 3 have different package system, so we can include both drivers into our classpath (i.e. `3.9.0` and `4.7.2`) as I did in this PR: #2169 

I still don't know what to do with `Dropwizard` conflicts because many of our dependencies depend on Dropwizard 3.2.6 but cassandra driver depend on Dropwizard 4.0.5.

**Comment by smcquillan** [comment]
@porunov Thanks for following up n this issue, I'll spend some time this week looking at your `datastax-cql-4.x` branch in my environment and see if there's anything I can do to help.

**Comment by porunov** [comment]
Thank you @smcquillan ! It will definitely help very much.
All CQL tests fail right now in that branch. I guess I made some obvious mistake there. It would be great if anyone could give any thoughts about it.
We don't have any problems with Dropwizard anymore because @farodin91 bummed it to 4.1.5 version in master branch. We also don't have any problems with using datastax 3 and 4 drivers together because they live under different packages.
