### ISSUE TITLE
how to improve the performance of writing to Janusgraph

### ISSUE THREAD

**Issue by Liuhaoxian** [JanusGraph/janusgraph#1511]
I used the Janusgraph+es+hbase in my project,and have tested the perfromance of writing entities to it, however the result is showed too much time cost during submitbing transaction. Is there a solution to deal it?

**Comment by porunov** [comment]
@Liuhaoxian Please, use the next group to post your questions: https://groups.google.com/forum/#!forum/janusgraph-users

GitHub issues are only for feature requests and bugs.

Also, to get answers your should provide more information about your test case (configuration, schema, indexes, test case code, result of the test case and expected behavior. I.e. anything which might be helpful to determine your problem). There are many ways to improve performance. It all depends on the situation.

**Comment by Liuhaoxian** [comment]
I am sorry to do it, and thanks for your suggestion.
