### ISSUE TITLE
GremlinServer returns HTTP 200 on commit failure

### ISSUE THREAD

**Issue by katshup** [JanusGraph/janusgraph#158]
If I open up a transaction through the GremlinServer and eventually encounter an error when calling 'g.tx().commit', the server response is the following:
`Message(status_code=200, data=[None], message=u'', metadata={})`

Ideally it should be error 500?

**Comment by pluradj** [comment]
Do you have a test case that demonstrates this?

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
