### ISSUE TITLE
Index update not working for Cardinality.SET in single transaction

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1583]
If we have a mixed index on a property with `Cardinality.SET` and perform remove and add value for this property in one transaction then remove is swallowed by the consolidation mechanism which assumes that there will be no need for deletion since old value will be replaced by a new one, which is not true for cardinality != `SINGLE`.

**Comment by porunov** [comment]
@FlorianHockmann @chupman I can't understand the difference between this issue and #1050 .

I see that #1575 is targeting this issue. Also I see that #1547 and #1588 are targeting #1050 .
As I understand if these PRs #1547 and #1588 are merged then this issue will be resolved. Am I right?

**Comment by chupman** [comment]
So I just took another look and can hopefully provide a clearer answer this time. PR #1575 is addressing deletions getting erroneously removed during index mutation consolidation.

It looks like #1547 and #1588 are giving the option to have values updated in-place instead of adding duplicates. In the event you would want a list with duplicate options having it be a config option and not a default makes sense. I'm ready to approve both once they get retargeted.

I think we need all 3 PRs and I'm sorry for creating any unneeded alarm. There was a lot of class inheritance to dig though and I was struggling to find the distinction yesterday.

**Comment by porunov** [comment]
Fixed by #1606
