### ISSUE TITLE
Bug OLAP cassandra authentication in 0.4.0

### ISSUE THREAD

**Issue by jacky92** [JanusGraph/janusgraph#1673]
Hi,

CQL OLAP authentication to cassandra not working.
conf/hadoop-graph/read-cql.properties 

janusgraphmr.ioformat.conf.storage.username=***
janusgraphmr.ioformat.conf.storage.password=***

Bug is in class "janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryInputFormat.java"
In CQL, not used ConfigHelper for username and password but CqlConfigHelper

Bug :
---------------------------
        if (janusgraphConf.has(GraphDatabaseConfiguration.AUTH_USERNAME)){
            ConfigHelper.setInputKeyspaceUserName(config, janusgraphConf.get(GraphDatabaseConfiguration.AUTH_USERNAME));

        }
        if (janusgraphConf.has(GraphDatabaseConfiguration.AUTH_PASSWORD)){
            ConfigHelper.setInputKeyspacePassword(config, janusgraphConf.get(GraphDatabaseConfiguration.AUTH_PASSWORD));
        }
---------------------------

Correction : 
---------------------------
        import org.apache.cassandra.hadoop.cql3.CqlConfigHelper;

        if (janusgraphConf.has(GraphDatabaseConfiguration.AUTH_USERNAME) && janusgraphConf.has(GraphDatabaseConfiguration.AUTH_PASSWORD)) {
            CqlConfigHelper.setUserNameAndPassword(config, janusgraphConf.get(GraphDatabaseConfiguration.AUTH_USERNAME), janusgraphConf.get(GraphDatabaseConfiguration.AUTH_PASSWORD));
        }
---------------------------

**Comment by porunov** [comment]
@FlorianHockmann would you be able to confirm if it is a bug?

**Comment by FlorianHockmann** [comment]
I just talked with @farodin91 about this as we implemented the CQL format together and it's indeed true that the format uses the old `ConfigHelper` from Thrift instead of the newer `CqlConfigHelper` that we should be using. The reason was apparently that the `CqlConfigHelper` didn't have all necessary options in the version of Cassandra we're currently using in JanusGraph. We should be able to switch to that when we update to a newer Cassandra version, but we have to drop support for Thrift first which we can't do before 0.5.0 as it's of course a major breaking change. (Note that this is only based on our recollection of work we did half a year ago. So, it would probably be best if someone could try this out with the version we now have in 0.4.0.)

@jacky92 Can you try to configure authentication with the config options the old `ConfigHelper` expects?

**Comment by jacky92** [comment]
Hi

Only authentication with CqlConfigHelper is OK. 

I have test several config with ConfigHelper without success... 

I use this change with spark-gremlin and it is OK. (I don't have activated ssl with cql for now)
