### ISSUE TITLE
Is the batch-loading=true valid for HBase underlying DB? 

### ISSUE THREAD

**Issue by edcSam** [JanusGraph/janusgraph#1718]
my underlying DB of my JanusGraph is HBase. The speed of bulk load is really slow. I know there are many factors effecting it, but I can not find the exact reason (I am trying). And I heard the batch-loading is only supporting for Cassandra. So is it true? Or it just exists in old version?

**Comment by FlorianHockmann** [comment]
As the text you deleted while creating this issue already indicated, we are not using issues for questions, but only for bug reports or feature requests. Please use [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) or our [Gitter chat](https://gitter.im/janusgraph/janusgraph) instead for questions like this one. (Since the question is quite specific, you'll probably have more luck on janusgraph-users.)
