### ISSUE TITLE
Add a new DefaultSchemaMaker that logs auto created objects

### ISSUE THREAD

**Issue by mmadoo** [JanusGraph/janusgraph#1917]
**Describe the feature:**
This DefaultSchemaMaker would extends / proxy the JanusGraphDefaultSchemaMaker and a WARN log when an object (edge, vertex, property, ...) is created.

**Describe a specific use case for the feature:**
Sometimes some property may have been forgot to add in the schema. This can be detected using the DisableDefaultSchemaMaker but it would fail the request. With this mode, such error can be seen by looking at logs (then schema can be fixed for next schema creation).

I could implements this improvement, but I would like to know if it might be accepted.

**Comment by FlorianHockmann** [comment]
Thanks for suggesting this feature and for also already providing a possible implementation. I think that we should however first decide whether we want to support this feature in JanusGraph or not.

I have some basic questions first to better understand the use case for this:
Why would you want to use the automatic schema maker if you want to maintain the schema on your own?
What do you do when JanusGraph informs you that you forgot to create a schema element with a log entry? It's too late any way to create it on your own as JanusGraph already created it with the default options. So, throwing an exception in this case seems like the much more sensible thing to do in my opinion.

**Comment by mmadoo** [comment]
I think that this feature could be usefull when migrating an existing project from automatic schema to user provided schema as such configuration can be set on production with a minimal impact and prevent regressions.
In our case, we have multiple janusgraph independant instances, thus we need often to create schema. Thus, even if it is too late to update on the janusGraph that has done the log, we could update the schema on other hosts.

**Comment by FlorianHockmann** [comment]
So, you're using the same schema in different JanusGraph graphs that are separated from each other?
I think that is really an edge case which is why my initial thought was to not support this in JanusGraph and instead suggest that you support this feature on your own.
However, logging the operations of the automatic schema maker is probably an interesting addition in general to make them more transparent to the user. It allows them to better understand when the schema was changed so they know when they should have modified the schema themselves, e.g., in test environments where changes are tested before using them in production.
For that reason, I'm in favour of supporting this directly in JanusGraph.

**Comment by FlorianHockmann** [comment]
Fixed by #1918.
