### ISSUE TITLE
When StandardJanusGraphTx releaseTranscation, the indexcache didn't cleanup.

### ISSUE THREAD

**Issue by TonyShen** [JanusGraph/janusgraph#1968]
I read the code , find the issues. 
1.When StandardJanusGraphTx releaseTranscation, the indexcache didn't cleanup.
2.Why other Transactions(BackendTransaction, IndexTransaction, etc.) havn't the cleanup(close) method.
Is it a bug?

Version: 0.4.1

**Comment by FlorianHockmann** [comment]
Please ask questions like these on one of [our community channels](https://github.com/JanusGraph/janusgraph#community), for example the [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) group. We are only using GitHub issues for (confirmed) bug reports and feature requests, as indicated in the text you deleted while creating this issue.
The second issue you mention is definitely a question. The first issue might be a bug report or also a question, but it misses important information, like which steps you performed, what the result was and what result you expected. It's easier to collect information like that and then decide whether it's a bug or not on janusgraph-users which is why we prefer to handle issues like this over there and then maybe create a GitHub issue afterwards if we have confirmation that it's actually a bug.
