### ISSUE TITLE
Add note on release branch merging to dev process docs

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#197]
Update development process documentation [docs/development.txt](https://github.com/JanusGraph/janusgraph/blob/master/docs/development.adoc) with note on the PR process (if applicable) for merging release branches into master (or other release branches).

In particular, should these merges be handled only by a repo admin who can bypass the PR process or, if committers can request/perform these merges can they be handled as CTR with a self-approval (if that's even possible)?

**Comment by FlorianHockmann** [comment]
Isn't our current policy to always merge release branches into `master` after we made a CTR commit to a release branch or merged a PR to ensure that the changes also land in `master`? Otherwise, we will always run into big merge conflicts that are ugly to resolve and might affect different code areas which makes it hard for a single committer to resolve the conflicts.

**Comment by sjudeng** [comment]
@FlorianHockmann Right, this issue is just here to track getting that guidance in the developer docs if it hasn't already been added. Also maybe it's changed but in the past only committers with admin access could merge into master (or a release branch) without a separate approval. Would be nice if that could be bypassed just for the case when merging from release branches to master, since that can (and should as you point out) be done often. But maybe GitHub doesn't provide that level of permission granularity.

**Comment by FlorianHockmann** [comment]
> Also maybe it's changed but in the past only committers with admin access could merge into master (or a release branch) without a separate approval.

Yes, looks like that was changed as I'm able to merge into `master` without any additional approval. This doesn't only affect merging release branches into `master` but also PRs directly into it which is often the case as most PRs target `master` instead of another release branch (`0.2` right now).
But I  agree of course in general that we should put these aspects into the docs as I'm also searching for some old posts on the mailing list from time to time to check what our current policy is regarding release branches and merging strategies.
