### ISSUE TITLE
Renaming janusgraph full and janusgraph truncated release

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#2068]
Suggestion to rename janusgraph-full to janusgraph. And janusgraph to janusgraph-truncated as described in https://groups.google.com/forum/#!topic/janusgraph-dev/qQRc8fT5aPw

**Comment by porunov** [comment]
@farodin91 what do you think about it? If you agree, would you be able to rename janusgraph distributions?

cc @FlorianHockmann

**Comment by farodin91** [comment]
I don't think this naming would better, because the distribution of `janusgraph-full` is opinionated version which include fixed version of cassandra and elasticsearch.
We have to manage version full for each new release of elasticsearch and cassandra check for new defaults. I think we can use our time for other parts in JanusGraph than managing the distribution. This is much better done by the original distributor. 

For user the uses different backends, they could think they are second class. (don't provide any version for them for example hbase) 
Futhermore with our the docker images, i think it much better to say new users, they should start testing janusgraph using docker. 

I'm would also much more prefer to remove the `janusgraph.sh`.

**Comment by porunov** [comment]
@farodin91 Thank you for your points. Agree with them, so I think we can close the issue. 
@FlorianHockmann please, reopen the issue if you think otherwise.

**Comment by FlorianHockmann** [comment]
No, I'm OK with keeping the names as is. @farodin91 provided a good explanation. It makes sense for us to concentrate on a small distribution that doesn't also include Cassandra and ES, especially now that we have a production ready inmemory backend.
We just need to make sure that it's still possible to start JanusGraph Server with a single command in the default distribution, but you're already taking care of that in #2067.
