### ISSUE TITLE
Separate out storage format version from JanusGraph version

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#232]
JanusGraph getting a bit hosed right now with versioning even though the [storage format](http://docs.janusgraph.org/latest/data-model.html) isn't changing. JanusGraph uses the release version for the storage format version. This makes it pretty cumbersome to test different versions without hacking the root `pom.xml` to update the `janusgraph.compatible-versions` or `titan.compatible-versions`. For example, if I created a graph based on the `v0.1.0` tag with the version `0.1.0`, it will throw an error if I try to connect to it from a build on the `0.1` branch with the version `0.1.1-SNAPSHOT`.
```
StorageBackend version is incompatible with current JanusGraph version: storage [0.1.0] vs. runtime [0.1.1-SNAPSHOT]
```
Separating the storage format version would make it easier to cope with more frequent releases.

**Comment by wojciechwojcik** [comment]
Setting e.g. 0.1.0 version to be compatible with 0.2.0 will have unwanted side effects. If the version stored in cassandra is set to 0.1.0, this also means that we allow connection using older and newer Janus clients to the same store at the same time. Even if schema did not change, the software side did for sure, which may lead to hard to deal with error with locks, caching, transactions etc. There has to be a way to actually migrate/upgrade the required version stored in cassandra db.

Even if we version schema independently from Janus software version for internal use (like migration procedures), I still think connections using older client versions should be prohibited or at least enabled via some extra setting in the connection properties.

**Comment by pluradj** [comment]
Fair enough. Client/server version checking can be added with in coordination with this.

**Comment by boliza** [comment]
any update on this issue?

>graph = JanusGraphFactory.open('conf/janusgraph-cql-es.properties')
StorageBackend version is incompatible with current JanusGraph version: storage [0.2.0-SNAPSHOT] vs. runtime [0.3.0-SNAPSHOT]
Type ':help' or ':h' for help.
Display stack trace? [yN]y
org.janusgraph.core.JanusGraphException: StorageBackend version is incompatible with current JanusGraph version: storage [0.2.0-SNAPSHOT] vs. runtime [0.3.0-SNAPSHOT]

**Comment by chupman** [comment]
I'm more than happy to help work on this issue. I'm hoping to get some guidance on what the approach should be though. 

Is the answer to replace the check that evaluate the storageBackenend against the janusgraph version with a client server check that makes sure only one version of client is connected at one time?

Or would it possibly be better to add support for an upgrade or testing property to the pom that relaxes the check rather than removing it all together?

**Comment by wojciechwojcik** [comment]
@chupman keep in mind there is no janus "server" here, you simply connect your janus java client directly to cassandra, so what we call today _schema version mismatch_ is actually the client-server check, where server is actually the cassandra itself.

Please correct me if I'm wrong, but from what I know there were no actual janus schema differences between all versions released so far, so perhaps the schema versioning is not that needed right now. 

What is really needed IMO is the option to upgrade the version stored in cassandra, so that when you upgrade your java client you still have the possibility to connect to the older database.
Ideally this could be done from the new janus client itself using some connect options or switches (e.g. upgrade=true). Alternatively maybe just some cassandra csql script is enough to make the offline migration.

Pom changes do not seem to be a solution here, as this is a runtime problem, not a build problem, and as you said only thing you could do if effectively remove this check at build time.

Again I am not a janus dev and this is just my user perspective.

**Comment by chupman** [comment]
I had a chance to discuss this more with Jason and he was kind enough to put his thoughts in a [gist](https://gist.github.com/pluradj/000ec07e6caf1c143ab3e7974879909a).  With the near possibility of schema enhancements this is probably becoming more important. 

I hoping to get some feedback on what the gist proposes before I start working on implementation.
