### ISSUE TITLE
Slow convert to Java object

### ISSUE THREAD

**Issue by Mirovan** [JanusGraph/janusgraph#2324]
Hi!

I am trying write select-query and my perfomance is very slow when I call method toList().
How I can improve this perfomace ?

My example:
```
        long start;
        long end;
        try (GraphTraversalSource g = graph.traversal()) {
            start = System.currentTimeMillis();
            
            GraphTraversal<Vertex, Vertex> list2 = g.V().hasLabel("Entity");

            end = System.currentTimeMillis();

            System.out.printf("getGremlinTime: %d ms\n", (end - start));

            start = end;
            List<Vertex> res2 = list2.toList();

            end = System.currentTimeMillis();
            System.out.printf("toList: %d ms\n gremlin count: %d\n", (end - start), res2.size());

        }
```

Debug log:
```
getGremlinTime: 13 ms
2020-12-31 14:19:01.336  WARN 14144 --- [           main] o.j.g.transaction.StandardJanusGraphTx   : Query requires iterating over all vertices [(~label = Entity)]. For better performance, use indexes
toList: 12025 ms
 gremlin count: 105
```

**Comment by li-boxuan** [comment]
This should be posted in https://github.com/JanusGraph/janusgraph/discussions/categories/q-a
Somehow I cannot find the "convert this issue to a discussion" button anymore - @farodin91 @porunov are you able to do it? Not sure if it's a permission thing.

@Mirovan Timing `GraphTraversal<Vertex, Vertex> list2 = g.V().hasLabel("Entity");` is meaningless. No actual query planning &  execution will happen until you call `toList()` (or `hasNext()`, `next()`, etc.).

As your log suggests,

> 2020-12-31 14:19:01.336  WARN 14144 --- [           main] o.j.g.transaction.StandardJanusGraphTx   : Query requires iterating over all vertices [(~label = Entity)]. For better performance, use indexes

It is slow because JanusGraph scans the entire database. JanusGraph does not support index for vertex label (https://github.com/JanusGraph/janusgraph/issues/283), so you could create a property (say, "type") and build a composite index for it. Then your query would be:

`g.V().has("type", "Entity").toList()`

which should be much faster.

**Comment by porunov** [comment]
@li-boxuan It looks like this feature is gone from GitHub. At least I don't see this button anymore. The GitHub documentation is explicitly saying that we should have `Convert to discussion` button on the right margin but it's not appearing there anymore.
https://docs.github.com/en/free-pro-team@latest/discussions/managing-discussions-for-your-community/moderating-discussions#converting-an-issue-to-a-discussion 
This also could be a bug on GitHub side.
