### ISSUE TITLE
Support multi-query in Cassandra backend

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#2406]
Currently, CQLStoreManager does not support multi-query:
https://github.com/JanusGraph/janusgraph/blob/4f3496202a5ca66f3dd47662255449eea379f5ed/janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java#L214

Not sure why it is not supported right now... It would be nice to add this support which could speed up multi-vertex properties retrieval.

Requested by https://github.com/JanusGraph/janusgraph/discussions/2401

**Comment by li-boxuan** [comment]
Seems this was by intention: see the opening comment of https://github.com/JanusGraph/janusgraph/issues/35 which recommends avoiding IN() clauses for selects. Need to investigate and evaluate if this still holds today, as that thread was a bit old.

**Comment by wen313** [comment]
I hope this function can be realized as soon as possible.

**Comment by li-boxuan** [comment]
I read some relevant resources and seems this is by design because IN() clause is not very efficient. However, as long as you `query.batch = true`, JanusGraph uses a thread pool to fire Cassandra queries concurrently, which should suffice the purpose of multi-query. In fact, this seems to be the recommended way to do multi queries in Cassandra.

**Comment by li-boxuan** [comment]
Closing this issue for now. Feel free to reopen if anything does not work as expected.

**Comment by benjamincoven** [comment]
Concurrent queries to Cassandra seem to not be handled properly, I get this exception:

`Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: host.docker.internal/_XXX.XXX.XXX.XXX_:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [host.docker.internal/_XXX.XXX.XXX.XXX_:9042] Pool is busy (no available connection and the queue has reached its max size 256)))
janusgraph  |   at com.datastax.driver.core.RequestHandler.reportNoMoreHosts(RequestHandler.java:283)
janusgraph  |   at com.datastax.driver.core.RequestHandler.access$1200(RequestHandler.java:61)
janusgraph  |   at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:375)
janusgraph  |   at com.datastax.driver.core.RequestHandler$SpeculativeExecution$1.onFailure(RequestHandler.java:450)
janusgraph  |   at com.google.common.util.concurrent.Futures$6.run(Futures.java:1310)
janusgraph  |   at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
janusgraph  |   at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:106)
janusgraph  |   at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1322)
janusgraph  |   at com.datastax.driver.core.GuavaCompatibility.addCallback(GuavaCompatibility.java:112)
janusgraph  |   at com.datastax.driver.core.GuavaCompatibility.addCallback(GuavaCompatibility.java:100)
janusgraph  |   at com.datastax.driver.core.RequestHandler$SpeculativeExecution.query(RequestHandler.java:400)
janusgraph  |   at com.datastax.driver.core.RequestHandler$SpeculativeExecution.findNextHostAndQuery(RequestHandler.java:359)
janusgraph  |   at com.datastax.driver.core.RequestHandler.startNewExecution(RequestHandler.java:139)
janusgraph  |   at com.datastax.driver.core.RequestHandler.sendRequest(RequestHandler.java:121)
janusgraph  |   at com.datastax.driver.core.SessionManager.execute(SessionManager.java:705)
janusgraph  |   at com.datastax.driver.core.SessionManager.executeAsync(SessionManager.java:142)
janusgraph  |   at org.janusgraph.diskstorage.cql.CQLStoreManager.lambda$null$28(CQLStoreManager.java:517)
janusgraph  |   at io.vavr.collection.Iterator$35.getNext(Iterator.java:1632)
janusgraph  |   at io.vavr.collection.AbstractIterator.next(AbstractIterator.java:34)
janusgraph  |   at io.vavr.collection.Iterator$34.getNext(Iterator.java:1510)
janusgraph  |   at io.vavr.collection.AbstractIterator.next(AbstractIterator.java:34)
janusgraph  |   at io.vavr.collection.Iterator$34.getNext(Iterator.java:1510)
janusgraph  |   at io.vavr.collection.AbstractIterator.next(AbstractIterator.java:34)
janusgraph  |   at io.vavr.collection.Traversable.foldLeft(Traversable.java:471)
janusgraph  |   at io.vavr.concurrent.Future.sequence(Future.java:549)
janusgraph  |   at org.janusgraph.diskstorage.cql.CQLStoreManager.mutateManyUnlogged(CQLStoreManager.java:499)
janusgraph  |   at org.janusgraph.diskstorage.cql.CQLStoreManager.mutateMany(CQLStoreManager.java:457)
janusgraph  |   at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStoreManager.mutateMany(ExpectedValueCheckingStoreManager.java:79)
janusgraph  |   at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:94)
janusgraph  |   at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:91)
janusgraph  |   at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
janusgraph  |   at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
janusgraph  |   at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.persist(CacheTransaction.java:91)
janusgraph  |   at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.flushInternal(CacheTransaction.java:139)
janusgraph  |   at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.commit(CacheTransaction.java:196)
janusgraph  |   at org.janusgraph.diskstorage.BackendTransaction.commitStorage(BackendTransaction.java:133)
janusgraph  |   at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:747)
...`

I am not a Cql expert but it seems that the request should be awaited before sending the next ones.

**Comment by li-boxuan** [comment]
Hi,

Looks like you need to increase storage.cql.local-max-requests-per-connection
(by default it’s 1024). Unfortunately it is a FIXED variable. This is made
MASKABLE on master (and upcoming 0.6.0 release).

Best,
Boxuan

「tartar ***@***.***>」在 2021年7月21日 週三，下午4:54 寫道：

**Comment by benjamincoven** [comment]
It works, thanks, but I fear it happens again with higher data volume. What do you mean by MASKABLE?

**Comment by li-boxuan** [comment]
MASKABLE means different janusgraph instances can have different settings.
Moreover, 0.6.0 will give you more control on the JanusGraph internal
thread pool, see
https://github.com/JanusGraph/janusgraph/pull/2700

「tartar ***@***.***>」在 2021年7月21日 週三，下午5:44 寫道：

**Comment by li-boxuan** [comment]
See
https://docs.janusgraph.org/basics/configuration-reference/ for a better
explanation of what “FIXED” and “MASKABLE” are.

「Boxuan Li ***@***.***>」在 2021年7月21日 週三，下午5:50 寫道：

**Comment by porunov** [comment]
Reopened this issue as I believe we can implement multi-query for Cassandra backend without using `IO` operator, but instead relay or the same async execution we are doing today.

**WIP** PR: #3760

**Comment from the closed duplicate issue #3759 :**

Thread pool which is used for multiQuery evaluation (`backend-cql`) is using a separate thread for each IO operation which is far from optimal and sometimes may require thousands of threads to be added just for IO operations. 

As discussed in the next issue: #3170 it will be more beneficial to use async queries execution for CQL storage backend and use CQL executor pool for results deserialization purpose only. We shouldn't use executor pool for IO operations when using CQL storage backend.
With this feature we will need only `processors_count * 2` threads for multiQuery evaluations instead of thousands (as it is required for optimal IO operations right now).
