### ISSUE TITLE
order().by(property) doesn't work with mixed index 

### ISSUE THREAD

**Issue by rkozmer** [JanusGraph/janusgraph#252]
Results from the mixed index are not sorted natively (in my case by Lucene). Instead the slow comparator is used.

Index looks like:
```
mgmt.buildIndex("typeName", Vertex.class).addKey(type).addKey(name).buildMixedIndex("typeName")
```
Query:
```
results = traversal().V().has("type", "person").order().by("name")
```

As already discussed with @twilmes on gitter, the LuceneIndex.getSortOrder(IndexQuery) is being called with this incomplete query, the order-part is missing:
```
[(type = person)](2000):typeName
```

**Comment by twilmes** [comment]
Thanks for entering this @rkozmer. I tracked this down to JanusGraph checking to see if the incoming Gremlin order comparators are instances of `ElementValueComparator`. It appears that this changed at some point on the TinkerPop side so we need to instead expect an `ElementValueTraversal`. I'll finish change up and push for review.

**Comment by severin83** [comment]
Is there any news on this issue? I'm experiencing the same problem with pre-release 0.2.0 (didn't try 0.1.1) and elasticsearch (bundled version).
I came across this discussion thread about a similar problem in TitanDB:
[https://groups.google.com/forum/#!topic/aureliusgraphs/JFNthKyiBRM](url)

I tried the test script that was posted by Daniel Kuppitz on 08.02.16, the script works in JanusGraph, I see the indices in elasticsearch being updated, and I get very bad timings (compare to the timings posted in above linked discussion thread):

== 10000 Vertices ==
[893.2463445299999, 1507908527096]

== 20000 Vertices ==
[2475.23476129, 1507908622394]

Thanks, br
Severin

**Comment by pluradj** [comment]
Looks like this fell off the radar for @twilmes. Based on his previous comments, the [`HasStepFolder`](https://github.com/JanusGraph/janusgraph/blob/v0.1.1/janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java#L69) class is where the fix needs to be made.

**Comment by twilmes** [comment]
Yes, thanks for the bump @severin83 & @pluradj. I'll take a look at this again.

**Comment by severin83** [comment]
I made a few changes, which fix the problem for me. I can't be sure if the code is totally correct, but it certainly works on some use cases I tried.
If you want to take over the changes, I attached the diff to this comment.
[hasstepfolder.diff.txt](https://github.com/JanusGraph/janusgraph/files/1394347/hasstepfolder.diff.txt)

**Comment by takaomag** [comment]
Is this already fixed?

**Comment by twilmes** [comment]
@severin83 @takaomag if you all have some time, can you test PR #842 out for this and confirm if it behaves as you expect?

**Comment by takaomag** [comment]
@twilmes Thank you for your PR.
Since I am not familiar with java, I have some questions.
Does this PR support Ranging also? That is, in case of order().by(prop).range(10, 10), mixed index returns only 10 elements sorted by prop?

I am currently use ES. It seems this PR supports all mixed index. Is it right?

**Comment by davidclement90** [comment]
Hi,
Your query will just return nothing because the low range is inclusive and the high is exclusive. (http://tinkerpop.apache.org/docs/current/reference/#range-step). If you want the first 10 elements sorted by prop it's _order().by(prop).range(0,10)_ or _order().by(prop).limit(10)_

IndexQuery do not support offset. So it just support ranging with no offset _range(0,10)_ (https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java#L213). Range with offset will be do in-memory with the high range as query limit.

And ES, the PR supports all mixed index.
