### ISSUE TITLE
Enable query.batch by default

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#3186]
AFAIK, most if not all users benefit from `query.batch` option (https://docs.janusgraph.org/configs/configuration-reference/#query). I don't see why we shouldn't enable it by default. A lot of new users won't bother reading docs carefully or tuning their configs, and they are likely frustrated by the poor performance without `query.batch`.

**Comment by porunov** [comment]
+1 for having `query.batch` enabled by default. Probably this change should be targeted to `1.0.0` version of JanusGraph

**Comment by FlorianHockmann** [comment]
I just wanted to create a PR for this so we can already include in the rc1 release candidate, but then I've noticed that we actually describe 3 different scenarios for batch processing [in our docs](https://docs.janusgraph.org/operations/batch-processing/):

* no batch processing (currently the default)
* unrestricted batch processing (would be the default if we only enable `query.batch`)
* limited batch processing (added by @rngcntr in #2516)

and I'm wondering whether _unrestricted batch processing_ is really the mode that we want to enable by default. Doesn't the _limited batch processing_ solve the problems that users might have with batch processing which is probably the reason why it has been disabled by default since early Titan days?

**Comment by rngcntr** [comment]
Unreasonably large backend queries are the only reason I can imagine for batch processing to be disabled.

+1 for `query.batch=true` and `query.limit-batch-size=true` by default.
