### ISSUE TITLE
In memory Index Backends support

### ISSUE THREAD

**Issue by aie0** [JanusGraph/janusgraph#358]
Is it possible to add (is it already supported) to set index backend as in-memory one - for testing purposes?

**Comment by pluradj** [comment]
A quick search for "Lucene in memory" yields a few examples,  so it seems like to should be possible. I've been using Lucene with a `storage.directory` under `/tmp` for simple testing.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
