### ISSUE TITLE
MaprDB Storage Backend

### ISSUE THREAD

**Issue by Garriee** [JanusGraph/janusgraph#394]
Hi, I am trying to make JanusGraph work with Storage Backend as MaprDB, need help on the changes needed. Thanks.

**Comment by jerryjch** [comment]
Can you use HBase client API to access MaprDB?

You can start by looking at the JanusGraph docs on HBase, and for code start by looking at HBaseStoreManager.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
