### ISSUE TITLE
“SKIP” causes side effects and the node creation failed.

### ISSUE THREAD

**Issue by ljhhuxiaoba** [JanusGraph/janusgraph#4336]
I execute 2 queries on my empty JanusGraph database ,and an error occurs.

JanusGraph version: 1.0.0
operating system: windows 10

first query:
g.addV().choose(__.V(), __.V(), __.identity().addV()).addV().project('a0').by(__.constant(1))

second query:
g.addV().choose(__.V(), __.V(), __.identity().addV()).addV().project('a0').by(__.constant(1)).skip(1)

The first query creates 2 nodes but the second creates 1 node.
And they are translated from "CREATE (n1) MERGE () CREATE (n2) RETURN 1 AS a0" and "CREATE (n1) MERGE () CREATE (n2) RETURN 1 AS a0 SKIP 1" respectively. The two Cypher queries should both create 2 nodes.

I use the plugin named [cypher-for-gremlin](https://github.com/opencypher/cypher-for-gremlin) to translate Cypher query to Gremlin query.

**Comment by FlorianHockmann** [comment]
The second query also only creates one vertex if the graph is empty with TinkerGraph (version 3.7.1). So, again I don't see a bug in JanusGraph here.
I just inspected three of the issues you reported where you posted Gremlin traversals created by `cypher-for-gremlin` and in all three cases I came to the conclusion that there is no issue with JanusGraph, but most likely with `cypher-for-gremlin`.
Inspecting these issues takes time and I think it's not warranted to invest time if you are just copying Gremlin traversals created by a tool which isn't maintained any more and where the traversals are often hard to read. (The traversal in #4340 consisted of 58 lines with proper formatting.)
So, I'm now also closing the other issues you created where you posted traversals from `cypher-for-gremlin` without further investigation since I assume that they are also about issues with `cypher-for-gremlin` and not with JanusGraph.

That of course shouldn't discourage you from raising issues in general in the future if you notice problems with JanusGraph, but please first verify whether your traversal is correct. If you are lacking experience with Gremlin for this, then you can also simply check whether the traversal works as you expect with TinkerGraph. If it works there but not with JanusGraph, then you probably really found an issue with JanusGraph which we would of course like to hear then :-)
