### ISSUE TITLE
No way to import csv dataset

### ISSUE THREAD

**Issue by eddywatta** [JanusGraph/janusgraph#440]
Dear Devs, 
I'm working with JanusGraph for a little University project. I have to load several CSV files like the attached ones. Is there a way to import that file immediatly or I have to create a java class that parse the file and loads the data into the db like the class GraphOfTheGodsFactory.java does? 
![person_0_0](https://user-images.githubusercontent.com/15802789/28781990-2bd8b238-760c-11e7-868d-714badf27619.JPG)

![person_knows_person_0_0](https://user-images.githubusercontent.com/15802789/28782142-9745ee28-760c-11e7-89cb-f19a65147b7a.JPG)

**Comment by blacknred0** [comment]
I think you will have to create a piece of code to import your graph.  AFAIK - I don't think there is a lib as part of JanusGraph that does this automatically, but you can look at [Gremlin Importer](https://github.com/mastayoda/gremlin-importer) which it might do what you would like to do.

**Comment by eddywatta** [comment]
Thank you for your feedback, I've already evaluated Gremlin Importer but with this kind of CSV I still need to parse the file. In this case, I think java is the best way to load my dataset.

**Comment by blacknred0** [comment]
👍

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
