### ISSUE TITLE
Question about cassandra backend limitations

### ISSUE THREAD

**Issue by mglusiuk** [JanusGraph/janusgraph#444]
Hi,

I have found janusgraph is very similar to titan. Could you please check my question and let me know what are real limitations for cassandra backend?

https://github.com/thinkaurelius/titan/issues/1383

**Comment by mbrukman** [comment]
@mglusiuk — JanusGraph is very similar to Titan because it is a fork of Titan. :-)

That said, GitHub issues are intended to be about specific feature requests or concrete bugs that need to be addressed; it's not a good forum for open-ended discussion or questions.

Would you mind posting your question on janusgraph-users@ mailing list, please? There are more folks following the mailing list to get these types of questions addressed.

**Comment by pluradj** [comment]
https://groups.google.com/d/msg/janusgraph-users/jOWIG629oWY/nLKRquWHBQAJ
