### ISSUE TITLE
Fix double-checked locking

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#48]
Fortify - Double checked locking does not work

Occurs in three places:
1. [ColumnValueStore.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/inmemory/ColumnValueStore.java#L191)
2. [StandardJanusGraphTx.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java#L617)
3. [StandardJanusGraphTx.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java#L641)

**Comment by sjudeng** [comment]
These are instances where high-performance lazy initialization is probably required. It might cause performance issues to remove the double lock (e.g. always check lock under `synchronized(this)`). It appears double-checked locking is possible since Java release 5.0 for `volatile` field initialization, so maybe the implementations can be updated to improve stability without significant impact on performance.

1. https://stackoverflow.com/a/3580658
2. http://www.oracle.com/technetwork/articles/javase/bloch-effective-08-qa-140880.html
3. https://www.securecoding.cert.org/confluence/display/java/LCK10-J.+Use+a+correct+form+of+the+double-checked+locking+idiom
