### ISSUE TITLE
Docs: Script should detect version and create dirs

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#484]
script `janusgraph/docs/build-and-copy-docs.sh`:

1. If `VERSION` is not set, defaults to `latest`. This is dangerous because newer versions could inadvertently overwrite older versions (e.g. building `0.2.0-SNAPSHOT` when `latest` should and does point to `0.1.1` release).
2. If the `VERSION` dir does not exist in the docs repo, the script fails.

So I don't know if I'm missing something but it seems like the script should detect the correct version and create the appropriate directory i.e. do the right thing.

**Comment by mbrukman** [comment]
When I first wrote that script, I didn't have a good way to detect the current version automatically. We now have that (see the `analysis/coverity-scan.sh` script which parses `pom.xml` file to get the current version) so that should be easy to fix.

The version checked for existence to prevent typos from creating too many new dirs that had no matching versions; once we have the above, we can automatically `mkdir` because the version is known to be correct.
