### ISSUE TITLE
Fix insecure randomness

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#49]
Fortify - Use SecureRandom instead of Random
1. [BackendOperation.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/BackendOperation.java#L49)
2. [ConsistentKeyIDAuthority.java](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/diskstorage/idmanagement/ConsistentKeyIDAuthority.java#L196)
3. [DistributedStoreManager.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/diskstorage/common/DistributedStoreManager.java#L106)
4. [ExpirationKCVSCache.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/ExpirationKCVSCache.java#L158)
5. [PartitionIDRange.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/placement/PartitionIDRange.java#L127)
6. [RandomRemovalList.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/util/datastructures/RandomRemovalList.java#L75)
7. [SimpleBulkPlacementStrategy.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/placement/SimpleBulkPlacementStrategy.java#L75)
8. [SimpleBulkPlacementStrategy.java](https://github.com/JanusGraph/janusgraph/blob/84ead7d/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/placement/SimpleBulkPlacementStrategy.java#L84)

**Comment by mbrukman** [comment]
I'm all for using `SecureRandom` vs. `Random`, but my understanding is that typically, more secure random generators require more entropy, and when you run out of such entropy sources, the consumers slow down while they wait for additional entropy. Are the uses of randomness really security-sensitive in JanusGraph? Should we be willing to pay a performance penalty by using more secure random generators?

Alternatively, users will need to use a workaround to avoid the slowdown, which will become a usability problem, which will impact user adoption: (a) user forgets / misses the docs about the workaround, (b) user finds the JanusGraph is too slow (due to the use of `SecureRandom`), (c) user never bothers asking on the mailing lists why it's slow, and instead chooses to evaluate something else.

Here are some references:
* [Stack Overflow: How to solve performance problem with Java SecureRandom?](http://stackoverflow.com/questions/137212/how-to-solve-performance-problem-with-java-securerandom)
* [The dangers of `java.security.SecureRandom`](http://www.mattnworb.com/post/the-dangers-of-java-security-securerandom/)
* [Stack Overflow: Slow service response Times : Java `SecureRandom` & `/dev/random`](http://stackoverflow.com/questions/27173833/slow-service-response-times-java-securerandom-dev-random)

In particular, it appears that `/dev/random` used as source of entropy blocks when there's not enough entropy data, thus causing the slowdown. Several sources suggest using `/dev/urandom` instead:

* [Oracle/BEA: Avoiding JVM Delays Caused by Random Number Generation](https://docs.oracle.com/cd/E13209_01/wlcp/wlss30/configwlss/jvmrand.html)
* [Stack Overflow: answer to one of the questions above](http://stackoverflow.com/a/2325109/3618671)
* [Myths about `/dev/urandom`](http://www.2uo.de/myths-about-urandom/)

That said, as per above, requiring users to make a manual workaround will affect user adoption, so this must be done automatically for them, without any extra manual steps on their part.

**Comment by sjudeng** [comment]
@amcp The explanation provided here by @mbrukman seems like a reasonable justification for these findings. It doesn't seem like we need the stronger randomness in these usages so it's probably not worth the extra performance cost. What do you think?

**Comment by amcp** [comment]
Not worth it.
