### ISSUE TITLE
JanusGraph transaction cache is never evicted

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#500]
In the caching reference section:
http://docs.janusgraph.org/0.1.0/config-ref.html#_cache
is it described that by default janus cache should be evicted automatically every 10 seconds.

It seems it only applies to global cache (disabled by default).
At the same time the transaction level cache NEVER expires (enabled by default).

Once a vertex property is read by a transaction, its value will never the re-fetched from the database.
This makes having long transactions impractical as data gets outdated.

The only way to actually evict the cache is to commit the transaction, which in turn closes it underneath.
It happens when using tinkerpop transation api (``graph.tx().commit()``) as well as with Janus explicit transaction api: ``graph.buildTransaction().start()``.

Furthermore even if the data is changed (commited) from another transaction within the same janus graph instance, the caches of other transactions are not notified and still serve stale data (there is NO cache coherence).

Steps to recreate:
1. Open two gremlin consoles and open connection to the same graph backend with some data already in it.
``graph = JanusGraphFactory.open("conf/storage-backend.properties"); g = graph.traversal(); ``

2. Read some vertex property from the first console, so it gets cached:
````
g.V(1).values('name')
=> old_name
````

3. Modify this vertex property on the second console and commit the changes.
````
g.V(1).property('name', 'new_name')
g.tx().commit()
````

4. Re-read the property on the first console:
````
g.V(1).values('name')
=> old_name
````

Notice the value will not get refreshed, not even after waiting for days.

The only way way to get the update value is to end the transaction by committing it
````
g.tx().commit()
g.V(1).values('name')
=> new_name
````
OR opening a new transaction:
````
t = graph.buildTransaction().start()
t.traversal().V(1).values('name')
=> new_name
````

This is especially problematic for read-only transactions, where you cannot safely keep a single long running transaction just for reading out the data. Each read-only request has to create its own transaction just to evict the cache.

So its either no cache at all OR cache that never gets refreshed, with no middle ground available by default.

**Comment by wojciechwojcik** [comment]
FYI @holleyism

**Comment by robertdale** [comment]
First, you are opening two independent embedded JanusGraph instances.  Unless you are also using a distributed cache, which isn't even supported, there is no communication between the two instances.

That said, even if you had opened two traversals on the same graph instance, I believe this is working as designed. Every read/write is within a transaction. The strategy is to call `g.tx().rollback()` between 'transactional boundaries' for reads. These transactions are fairly lightweight. Is the concern one of performance? I clocked `g.V().next()` with and without a following call to `tx()`.  With commit/rollback (there was no difference), I get  0.007ms/tx overhead (140 tx/ms).  Without calling commit/rollback, I get 0.004ms/tx overhead (238 tx/ms).

I think updating the transaction cache would violate any sort of transaction isolation. 

1. http://tinkerpop.apache.org/docs/current/reference/#transactions
2. http://docs.janusgraph.org/latest/tx.html#_transaction_handling

**Comment by robertdale** [comment]
Correction, the timings are **total tx time** including the query execution. Thus, the tx _overhead_ would be rollback time - none time = 0.003 ms/tx.

**Comment by wojciechwojcik** [comment]
There a couple of issues here:

1. Documentation. None of the docs linked above mention anything about caching behavior. Janus cache reference gives a false impression of 10s standard evict time, which is no true. They also state that enabling global cache increases the changes of hitting stale data, while the problem occurs also when cache is set to false, which is further misleading.

2. Cache coherence. I've given example of two independent instances for simplicity sake, yet the same issue occurs when **already committed** data from one transactions on the same instance does not trigger cache eviction for other transactions that are in progress. Thus is seems there is no perf benefit of having single graph instance over many independent ones. 

3. None of the docs mentioned here say that value read within one transaction should never change.
In the classic RDBMs systems you have control over transaction isolation levels and what potential issues you may face (e.g. non-repreatable reads, phantom reads, uncommited reads). 
And even if you set in RDBMs the level to serializable to avoid non-repreatable reads, the read value does not change not because it is cached forever, but because it is locked on db level for changes by others. Still a read request to db is a read request, not a fake one like in Janus.
I think me are mixing up the transaction isolation here (which is not guaranteed on cassandra I'm using anyways), with broken cache behavior.

I'm opening an issues because I learned all of this the hard way. Even if design is 'correct' here, there is definitely a room for improvement here, even if on doc level only if not for perf.

**Comment by robertdale** [comment]
I'm all for improving docs. Perhaps you can make some suggestions for making it clearer?

1. Documentation
- Have you looked at the [JanusGraph Cache](http://docs.janusgraph.org/latest/caching.html) page?
- Where did you find an implied '10s standard evict time'?  Let's correct that.
- There is no 'global' cache. Some cache configuration options have global _mutability_ which has to do with changing the configuration, not how or what layer the cache is available.  Do you mean transaction cache (vertex cache, index cache) or database-level cache?

2. Cache access goes like this:  transaction -> transaction-level cache -> database-level cache -> backend database. The caches are within the JanusGraph instance and give a performance boost.  So if you follow the pattern of rollback before or after read, you still use the database-level cache within `db-cache-time` instead of hitting the database.  The database-level cache is invalidated on commit within the same graph instance.

3. Transaction read value
- Again, have you read [JanusGraph Cache](http://docs.janusgraph.org/latest/caching.html) ?
- There are no transaction-level cache invalidation or expiration times expressed or implied that I can see. There is `cache.tx-cache-size`.  There's a min tx-cache-size of 100 due to thinkaurelius/titan#893 . The tx appears to pick up new vertices (I did not try indexed values) but it does not recognize new or mutated _properties_ on those vertices once cached.  But think about it:  What would happen if properties were externally changing mid-traversal?  One moment it's there, another it's gone.  'Action at a distance'.
- Avoid long-running transactions e.g. `read, compute, read more, compute, mutate, commit`.  Use transactions around the smallest unit of work e.g. `read, rollback`, compute, `read, rollback`, compute, `mutate, commit`.

**Comment by robertdale** [comment]
Ok, I think you are referring to `cache.db-cache-time` for 10s default.  This is correct.  However, this  impacts only the database-level cache.  Verified working.

**Comment by wojciechwojcik** [comment]
The JanusGraph Cache doc page only says that:  _modified vertices are pinned in the cache, which means they cannot be evicted since that would entail loosing their changes._. So its not the same as all read vertices are always pinned, which seems to be the case here.

The fact that even read-only transactions require you to rollback changes after each request were remotely mentioned only here: http://tinkerpop.apache.org/docs/current/reference/#transactions
I can't seem to find it anywhere in Janus docs or any code example that would follow this trend really.

If you still feel no doc/code changes are necessary, then please close the issue. 
I've learned enough on how to use it along the way and will not pursue the issue further.

**Comment by palwe-prafulla** [comment]
I have a similar issue.
Thread 1 - gets the current vertex data  which is invalid and fails.
Thread 2 - updates the data for the same vertex and commits.
Thread 1 - Again tries to get the data and fails as it doesnt see any update.

Based on Janusgraph and tinkerpop documentation suggested above.

I have updated the code in Thread 1 to rollback the transaction at the beginning.
This way whenever it comes back the stale data/tx from previous attempt is closed and cache is evicted.
However it does not work for some reason.

I am not sure whats going on.
I had individual rollbacks in the code whenever it fails and I updated the code to remove those individual roll backs on failures and added single rollback at the beginning to take care of it all.
However since its not working I am not sure if the individual rollbacks at failure before returning has any advantages/stability of clearing cache at that time over rolling back at the beginning which keeps the transaction open for a while until next attempt?

This is eating my brains as I do not see any valid reason for now for rollback at the beginning to not work.

**Comment by palwe-prafulla** [comment]
> I have a similar issue.
> Thread 1 - gets the current vertex data which is invalid and fails.
> Thread 2 - updates the data for the same vertex and commits.
> Thread 1 - Again tries to get the data and fails as it doesnt see any update.
> 
> Based on Janusgraph and tinkerpop documentation suggested above.
> 
> I have updated the code in Thread 1 to rollback the transaction at the beginning.
> This way whenever it comes back the stale data/tx from previous attempt is closed and cache is evicted.
> However it does not work for some reason.
> 
> I am not sure whats going on.
> I had individual rollbacks in the code whenever it fails and I updated the code to remove those individual roll backs on failures and added single rollback at the beginning to take care of it all.
> However since its not working I am not sure if the individual rollbacks at failure before returning has any advantages/stability of clearing cache at that time over rolling back at the beginning which keeps the transaction open for a while until next attempt?
> 
> This is eating my brains as I do not see any valid reason for now for rollback at the beginning to not work.



> I have a similar issue.
> Thread 1 - gets the current vertex data which is invalid and fails.
> Thread 2 - updates the data for the same vertex and commits.
> Thread 1 - Again tries to get the data and fails as it doesnt see any update.
> 
> Based on Janusgraph and tinkerpop documentation suggested above.
> 
> I have updated the code in Thread 1 to rollback the transaction at the beginning.
> This way whenever it comes back the stale data/tx from previous attempt is closed and cache is evicted.
> However it does not work for some reason.
> 
> I am not sure whats going on.
> I had individual rollbacks in the code whenever it fails and I updated the code to remove those individual roll backs on failures and added single rollback at the beginning to take care of it all.
> However since its not working I am not sure if the individual rollbacks at failure before returning has any advantages/stability of clearing cache at that time over rolling back at the beginning which keeps the transaction open for a while until next attempt?
> 
> This is eating my brains as I do not see any valid reason for now for rollback at the beginning to not work.

This issue has nothing to do with cache, it was an application issue on our side and it works correctly with rollback
