### ISSUE TITLE
Automate verification of license headers

### ISSUE THREAD

**Issue by mbrukman** [JanusGraph/janusgraph#525]
As pointed out in issue #522, we can get into a situation where some files are missing license headers (or have duplicate or incorrect headers). In other cases, reviewers have had to manually point out to contributors that the new files they were adding were missing license headers.

It should be possible to automate this verification as a test, so that files are not committed to the repository without having a header, and this check is done automatically, without relying on manual reminders from maintainers, or after-the-fact fixes such as PR #523.

Some options for implementing this are:

* http://www.mojohaus.org/license-maven-plugin/
* http://checkstyle.sourceforge.net/config_header.html

and there may be other alternatives available as well.

**Comment by FlorianHockmann** [comment]
I started working on this and noticed that the repository contains a lot **(150+) of files without any license header**. These files are mostly config files (`.properties`, `.yaml`, ...), docs (`.asciidoc`, `.md`) and bash scripts, but also some source files. So, I wonder whether we can now simply add a license header to all of these files or whether we need to check for each file individually who contributed it originally and whether we (as _JanusGraph authors_) own the copyright, especially for files that already existed in Titan.

Apart from that, I noticed that some open source projects move away from including a full license header in every file and instead just include the **SPDX license identifier**. [SPDX](https://spdx.org/) is a project under the Linux Foundation which tries to standardize the way in which metadata about licenses is published. [The kernel for example moved](https://lwn.net/Articles/739183/) to SPDX license identifiers. Our license header would than shrink to just:
```
// SPDX-License-Identifier: Apache-2.0
```
instead of the 13 lines like it is now. (We might still need the copyright line though.) So, the license header has a lot less overhead, especially for very small config files where the license header would currently be longer than the content.

If we now have to add license headers to 150+ files, then I think that it's a good opportunity to evaluate whether we want to move to SPDX or not.

Regarding the implementation of doing the license checks, I tried the [MojoHaus License Maven Plugin](http://www.mojohaus.org/license-maven-plugin/) as well as well as [this other license maven plugin](https://github.com/mycila/license-maven-plugin), but both didn't work with the license headers we currently have in JanusGraph. The MojoHaus plugin seems to only accept the comment style `/* ... */` instead of the `//` style we use and the second plugin seems to always need an empty start and end line (at least I didn't find a way to configure them differently). This means that we would have to change the license headers in **all** files to comply to the format these plugins are expecting. I don't think that it's worth to do that just to be able to use such a plugin.

I never used checkstyle and I didn't want to introduce it to JanusGraph for the sole purpose of checking license headers. Therefore, I tried [Apache Rat](https://creadur.apache.org/rat/) which is also the tool TinkerPop uses for its license checks and that was straight-forward to configure for JanusGraph. The only downside I found is that it seems to only look for the presence of a certain string in each file. For the Apache v2 license, this string is the URL that contains the full license and every file passes the check that contains this URL somewhere. So, the plugin doesn't really enforce the presence of a license header and it also doesn't verify the full content of the header. It is satisfied if it finds just this URL. I think that it's unlikely that someone will a license header that contains this URL, but doesn't really match the license text, so we can probably live with this limitation. But SPDX would also basically solve this problem for us as it would reduce the license header to a single line which we could use for the match (assuming that we don't need the additional copyright line).

**Comment by FlorianHockmann** [comment]
Fixed in #1411
