### ISSUE TITLE
JanusGraph examples

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#530]
It would help to on-board new users with example code on how to write an application that uses JanusGraph with the various storage and indexing backend configurations. `GraphOfTheGods` does this in part, but it isn't a standalone code example that a developer could easily clone and replace the logic to build and query their own.

**Comment by mbrukman** [comment]
@pluradj, do you think it would make sense to create a separate examples repo, outside of the main JanusGraph repo, so that it's easy to clone as-is, rather than a directory within the JanusGraph repo?

I was wondering whether it would be confusing to new users to download the entire source repo, which has a lot content and files of the JanusGraph implementation itself, which they don't need to examine, if they're just using `pom.xml` files to pull down the pre-compiled JARs from Maven anyway.

We can certainly start with a directory in the main repo, as your commit appears to do, just wanted to get your thoughts on what you think the long-term strategy should be.

**Comment by pluradj** [comment]
A standalone repo might make sense for additional examples, but I thought it would be good to  start with something small that is packaged with the main distribution. PR #531 creates an `examples` directory in the `janusgraph-0.2.0-hadoop2.zip` file containing all of the example source code and `pom.xml` files for building.

**Comment by sjudeng** [comment]
@pluradj Sorry I was just late to provide feedback: https://github.com/JanusGraph/janusgraph/pull/531#pullrequestreview-64764099.
