### ISSUE TITLE
The time for publish JanusGraph 0.2.0

### ISSUE THREAD

**Issue by Luminginx** [JanusGraph/janusgraph#532]
Can you tell me about the release date of JanusGraph 0.2.0 ? The feature for new version make me excited.

**Comment by IDerr** [comment]
By the way, since a few companies use JanusGraph in production.
Will it be considered as production-ready ?

**Comment by Luminginx** [comment]
In my company we used our modified version Titan 1.0.0 for a long time, only a few features were used.
Althought have many limits, the cluster is good running. 
In my opinion,  JanusGraph can be used in some limited scenarios, but it is not considered as production-ready.

**Comment by mbrukman** [comment]
@IDerr wrote:

> By the way, since a few companies use JanusGraph in production.
> Will it be considered as production-ready ?

Neither the JanusGraph development team, nor The Linux Foundation, are in a position to "declare" JanusGraph as production-ready, since they are not the ones maintaining or supporting it for anyone directly. It is up to the user community to decide whether or not JanusGraph meets the requirements for a production system.

As you pointed out, [many users](https://github.com/janusgraph/janusgraph/#users) feel that it is stable enough to run in production. Keep in mind that the version number 0.x should not be taken to imply a lack of stability or usefulness — JanusGraph 0.1 was forked from the unreleased Titan 1.1 branch, and many companies already ran Titan 1.0 and code from the Titan 1.1 branch in production, and were quite comfortable with it. JanusGraph 0.x is already ahead of where Titan 1.1 was, so it should be considered more up-to-date, but bringing in newer versions of dependencies may present a stability risk.

There are certainly a large number of tests both within JanusGraph and within the TinkerPop suite, and we aim to make sure all tests are passing both on the `master` branch and definitely for every new release; however, there is no explicit certification or guarantee of production readiness. All we can ask is that you try it out and let us know if it works for you, and file bugs or submit feature requests if it does not work well enough for you to use in production.

**Comment by mbrukman** [comment]
@Luminginx wrote:

> In my company we used our modified version Titan 1.0.0 for a long time, only a few features were used.

Are there any patches you made for Titan that you would like to share with the JanusGraph community? Pull requests are always welcome; we just ask that you [sign the CLA](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md).

> In my opinion, JanusGraph can be used in some limited scenarios, but it is not considered as production-ready.

Can you share what specific concerns you have that need to be addressed prior to you considering it production-ready?

Earlier, @Luminginx wrote:

> Can you tell me about the release date of JanusGraph 0.2.0 ? The feature for new version make me excited.

Are you looking to run JanusGraph 0.2.0 in production (to replace Titan), or will it also not be ready for your use case?

**Comment by Luminginx** [comment]
@mbrukman wrote:
> Can you share what specific concerns you have that need to be addressed prior to you considering it production-ready?

In the process of use, I found that multiple instances or transactions still had a situation where reading and writing were inconsistent. I don't know what the solution is, but in a cluster that has a large number of data to read and write frequently, single instance single transaction can have a performance limit. (We used HBase and elasticsearch as storage and index, a database has about 100 million vertexes and  2 billion edges.)

>Are you looking to run JanusGraph 0.2.0 in production (to replace Titan), or will it also not be ready for your use case?

In fact, we are ready to replace Titan with JanusGraph. The migration preparation is now underway.
During the previous use of Titan, our main modifications were to upgrade HBase and elasticsearch versions.

**Comment by IDerr** [comment]
Thanks @mbrukman for all these answers.

**Comment by pluradj** [comment]
I've started a thread to discuss the release on [janusgraph-dev](https://groups.google.com/d/msg/janusgraph-dev/PJF8qdoe_Zo/2JU-M4UQBwAJ)

**Comment by mbrukman** [comment]
FYI, v0.2.0 has been released: https://github.com/JanusGraph/janusgraph/releases/tag/v0.2.0
