### ISSUE TITLE
additional Gremlin documentation

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#576]
Iterating the traversal is one of the most common problems for new users.

Provide links to additional documentation resources, language drivers, and language variants.

Also, there are few example Gremlin calls that need to be moved to TP 3.x syntax, like

graph.shutdown() -> graph.close()
graph.commit() -> graph.tx().commit()

**Comment by liuyt-15** [comment]
hi，I meet a problem about gremlin language .
![image](https://user-images.githubusercontent.com/22389288/53395105-f99dcc00-39db-11e9-870b-6ea54910ca7a.png)
It shows that  "where(out('xx').is(eq('b')) " does not work because node_id = 491584 has the same target_node with 9019480.
I'm looking forward to receiving your message.
Thanks!

**Comment by FlorianHockmann** [comment]
@liuyt-15 Please don't ask usage questions in issues. Instead, you can ask such question in our [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) Google group or in our [Gitter chat](https://gitter.im/janusgraph/janusgraph).
