### ISSUE TITLE
Sync UPGRADE.asc and CHANGELOG.asc with docs

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#610]
These files are redundant to `docs/upgrade.txt` and `docs/changelog.txt`, respectively. They should either be removed or kept up-to-date with the docs versions.

**Comment by mbrukman** [comment]
I think this is a historical artifact of how Titan was released and how the docs were managed.

I agree that just copying them over on a regular basis doesn't make much sense; we should just link to the GitHub versions or the website versions (either `latest` or for a specific version) if either of these docs are necessary.

The only trouble with the GitHub version is that since they're .txt files, GitHub doesn't render them properly, but renaming them to .asc makes GitHub properly render them, which means:

* either we can only link to the published versions on the website, or
* we rename all of the AsciiDoc files from `*.txt` to `*.asc` to get proper rendering

I'm fine with either of these.

**Comment by robertdale** [comment]
I think we should define what docs are intrinsic to the code repository and/or should be github-facing vs. what is user-facing documentation.

I also agree that all asciidoc files should be renamed to have .asc (or one of the many others) file extension anyway.

**Comment by sjudeng** [comment]
@mbrukman, @robertdale Do we want to move forward with the copy one more time and tackle the wider fix in the next release? Current [release process](https://github.com/JanusGraph/janusgraph/blob/master/RELEASING.md#preparing-documentation) indicates these files should be synced up. I'd be in favor of keeping the current process just for 0.2.0 and fixing it after.

**Comment by robertdale** [comment]
I think that makes sense. Let's not hold up the release pondering this.

**Comment by mbrukman** [comment]
@sjudeng — I agree with following the release process as-is for 0.2.0, and update it afterwards to stop doing this.
