### ISSUE TITLE
Error on Enroll Custom AttributeSerializer

### ISSUE THREAD

**Issue by HackingJ** [JanusGraph/janusgraph#642]
In my case, I config like below
```
JanusGraph graph = JanusGraphFactory.build()
... //other config
        .set("attributes.custom.attribute1.attribute-class", "java.util.LinkedHashMap")
        .set("attributes.custom.attribute1.serializer-class", "my.package.MySerializer").open()
```

And I encountered error and received below messge
`Caused by: java.lang.IllegalStateException: Need to set configuration value: root.attributes.custom.attribute-class`

my.package.MySerializer is extended from org.janusgraph.graphdb.database.serialize.attribute.SerializableSerializer

I try to method below link, but not worked

https://github.com/pluradj/janusgraph-attribute-serializer
https://stackoverflow.com/questions/28669190/java-lang-illegalstateexception-while-configuring-custom-attribute-serializer-in

modifying attribute1 to attributeX(X is arbitary number) is not worked

I use janusgraph 0.1.1

thanks for your help

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
