### ISSUE TITLE
Could not instantiate implementation: org.janusgraph.diskstorage.es.ElasticSearchIndex

### ISSUE THREAD

**Issue by 444728248** [JanusGraph/janusgraph#679]
hello
I started hbase and didn't use es, but I made the following error

my hbase config
[root@master janusgraph]# cat conf/janusgraph-hbase.properties 
storage.backend = hbase
storage.hostname = master:2181,slave2:2181,slave2:2181
cache.db-cache = true
cache.db-cache-clean-wait = 20
cache.db-cache-time = 180000
cache.db-cache-size = 0.5
gremlin.graph = org.janusgraph.core.JanusGraphFactory
storage.hbase.ext.zookeeper.znode.parent = /hbase

error
Could not instantiate implementation: org.janusgraph.diskstorage.es.ElasticSearchIndex

**Comment by pluradj** [comment]
You probably connected initially with with `conf/janusgraph-hbase-es.properties`. This creates a configuration in the `janusgraph` HBase table with Elasticsearch as the indexing backend. If you attempt to connect afterwards with `conf/janusgraph-hbase.properties` you would see the error you described. This is because the previous configuration is stored in the `janusgraph` table itself.

What you should do is either:

- drop the `janusgraph` table in HBase
- add a `storage.hbase.table=newtablename` property into your properties file, using a different value than the default (`janusgraph`)

If those suggestions don't help, please update this issue with more details, like the full stack trace.

**Comment by pluradj** [comment]
Also note, this issue has been discussed previously on the [`janusgraph-users`](https://groups.google.com/d/msg/janusgraph-users/CckUAITr4ak/ZMhc--qeAQAJ) group and also on [Stack Overflow](https://stackoverflow.com/questions/46545611/using-janusgraph-with-solr). I'd recommend searching those places for possible solutions.

**Comment by Shamsa279** [comment]
You said : drop the janusgraph table in HBase
add a storage.hbase.table=newtablename property into your properties file, using a different value than the default (janusgraph)
How can I drop the table?

**Comment by patrickboland4** [comment]
@Shamsa279 just in case you're still stuck - https://www.guru99.com/hbase-shell-general-commands.html  note that you need to disable hbase tables prior to deleting them.

**Comment by iamsatyajit963** [comment]
Hi,@pluradj 
if we drop the hbase janus table, then what about existing data, which are in the table?
