### ISSUE TITLE
About partition question

### ISSUE THREAD

**Issue by haotong00** [JanusGraph/janusgraph#728]
①I create schema with partition. same as [graph-partitioning](http://docs.janusgraph.org/latest/graph-partitioning.html).  

```
mgmt = graph.openManagement()
mgmt.makeVertexLabel('user').make()
mgmt.makeVertexLabel('product').partition().make()
mgmt.commit()

```
②And add properties.
```
cluster.partition = true
cluster.max-partitions = 32
ids.flush = false
```
③insert vertexes with buckloader.

How can I check the partition whether success or not ? 
How can I get the partition's info through gremlin cmd?

**Comment by mbrukman** [comment]
@haotong1987 — for open-ended questions or discussions, please use the mailing lists or chat which are listed on the main page: https://github.com/janusgraph/janusgraph/#community

GitHub issues are for reporting specific, concrete feature requests or for submitting bug reports.

**Comment by chupman** [comment]
Based off the information in issue #878, and this [google groups thread](https://groups.google.com/forum/#!msg/janusgraph-dev/_DipC0FT2E4/f9r-Y_i4AgAJ), I think the answer is that graph partitioning is not supported and the documentation is being updated. While it's probably not what you were hoping for does that answer your question @haotong1987 ?

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
