### ISSUE TITLE
Update 0.3 (master) to TinkerPop 3.3.1

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#845]
- [x] Release TinkerPop 3.3.1
- [x] Pass TinkerPop tests - `mvn clean install -Dtest.skip.tp=false`
- [ ] Update gremlin-server.sh
- [ ] Update data files
- [ ] Update docs

**Comment by robertdale** [comment]
Announcement:  https://groups.google.com/d/msg/gremlin-users/GnDEGz6VXhY/oWIJtMkhBwAJ

**Comment by chupman** [comment]
For the Update gremlin-server.sh checklist item would it be possible to add support for environment variables to point at different yaml files in addition to running as a daemon? 

For example if "JANUSGRAPH_MANAGER =  true" gremlin-server.sh would append conf/gremlin-server/gremlin-server-configuration.yaml as a parameter instead of conf/gremlin-server/gremlin-server.yaml. Rather than expecting true/false it could be a string so it could easily be used for the berkeleyje config or any new default configs in the future.

I'm more than happy to submit a PR if you agree with the proposed changes.
