### ISSUE TITLE
janusgraph cannot reindex

### ISSUE THREAD

**Issue by buzhidaowenwen** [JanusGraph/janusgraph#865]
I built in janusgraph in the application, using hbase as the bakend storeage and es as the index storage. I lead in the data, then create the index, the index cannot take effect. As the same way, I disable the index, cannot enable it.

**Comment by robertdale** [comment]
Please provide steps to reproduce.

**Comment by buzhidaowenwen** [comment]
janusGraphProvider.init();
            JanusGraphManagement mgmt = janusGraphProvider.graph().openManagement();
            //JanusGraphIndex index = mgmt.getGraphIndex("byNameUnique");
            PropertyKey name = mgmt.getPropertyKey("name");
            JanusGraphIndex index = mgmt.buildIndex("byNameMixed", Vertex.class).addKey(name).buildMixedIndex("search");
            mgmt.commit();


            mgmt = janusGraphProvider.graph().openManagement();
            mgmt.updateIndex(mgmt.getGraphIndex("byNameMixed"), SchemaAction.REINDEX).get();
            mgmt.commit();

**Comment by buzhidaowenwen** [comment]
@robertdale Can you help me see where the problem is?

**Comment by robertdale** [comment]
1. You should wait for the index to transition to registered before re-indexing it.
`ManagementSystem.awaitGraphIndexStatus(graph, 'byNameMixed').status(SchemaStatus.REGISTERED).call()`
2. What is the definition of PropertyKey `name`?
3. After re-indexing, verify index is enabled.
`ManagementSystem.awaitGraphIndexStatus(graph, 'byNameMixed').status(SchemaStatus.ENABLED).call()`
4. Where's your query that shows the index is not being used?  After verifying the index is enabled, also show the `.profile()` on the query.

**Comment by buzhidaowenwen** [comment]
@robertdale I try again to get the following results,Still not successful.

![image](https://user-images.githubusercontent.com/11647791/34703997-099d0774-f531-11e7-8a23-7d786f32f6a3.png)

This step cannot be executed when it is executed.
![image](https://user-images.githubusercontent.com/11647791/34703873-62ecfeca-f530-11e7-8d43-dec2ca4e257b.png)

This is the definition of the schema.
![image](https://user-images.githubusercontent.com/11647791/34704022-331dc41c-f531-11e7-9610-a488800107ca.png)

**Comment by buzhidaowenwen** [comment]
When I did the tests on the gremlin server in accordance with the official test case, I still didn't succeed. I didn't know what went wrong.

official test case:




my test steps:

**Comment by robertdale** [comment]
It appears your index is stuck in INSTALLED.  For troubleshooting, see https://stackoverflow.com/questions/40585417/titan-db-ignoring-index/40591478#40591478

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
