### ISSUE TITLE
Remove config cluster.partition

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#878]
https://groups.google.com/d/msg/janusgraph-dev/_DipC0FT2E4/f9r-Y_i4AgAJ

> The documentation needs to be updated. The config cluster.partition = true is no longer used as it is commented out in the source.

**Comment by chupman** [comment]
I found the commit where the settings were commented out. https://github.com/thinkaurelius/titan/commit/05a7cff906d91f26186603b90f12575ebe55b338

I've read through the commit and think I have a good enough understanding of the current;y available options to update the partitioning doc.

**Comment by mbrukman** [comment]
@chupman -- FYI, since we brought over the entire history of Titan as-is, the same commits are present in JanusGraph, verbatim, e.g., this commit is also available as https://github.com/JanusGraph/janusgraph/commit/05a7cff906d91f26186603b90f12575ebe55b338 in thsi repo: exactly the same commit hash, I just changed the project org and project name.

**Comment by chupman** [comment]
Thanks @mbrukman. I was originally searching through PRs and couldn't find the commit, but didn't think about checking janusgraph again once I realized PRs weren't used in the old titan project.
