### ISSUE TITLE
PartitionIDRange warning

### ISSUE THREAD

**Issue by everlylfc** [JanusGraph/janusgraph#905]
So I started seeing these issues whenever I open a graph using the graph factory. I haven't been able to pinpoint the cause of the warning. I did some research and didn't find too much on it, but I did find that it was somewhat related to graph partitioning and id block size configuration.

I was wondering - is this something I should worry about resolving? What are the effects of this warning on my JanusGraph installation?

> 08:05:59 WARN  org.janusgraph.graphdb.database.idassigner.placement.PartitionIDRange  - Individual key range is too small for partition block - result would be empty; hence ignored: KeyRange(left:  63-255-255-252, right:  76-204-204-200)

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
