### ISSUE TITLE
getEdgeLabels does not exist on org.janusgraph.graphdb.database.management.ManagementSystem

### ISSUE THREAD

**Issue by dancollins34** [JanusGraph/janusgraph#910]
Hello,

It looks like while the management system created by ConfiguredGraphFactory.open(graph_name).openManagement() has a getVertexLabels() method, it is lacking a getEdgeLabels() method.  Could this be added?

Thank you,

Daniel Collins

**Comment by pluradj** [comment]
The [`getVertexLabels()`](https://static.javadoc.io/org.janusgraph/janusgraph-core/0.2.0/org/janusgraph/core/schema/JanusGraphManagement.html#getVertexLabels--) method comes from the [`JanusGraphManagement`](https://static.javadoc.io/org.janusgraph/janusgraph-core/0.2.0/org/janusgraph/core/schema/JanusGraphManagement.html) interface. For edge labels, you could use [`getRelationTypes(EdgeLabel.class)`](https://static.javadoc.io/org.janusgraph/janusgraph-core/0.2.0/org/janusgraph/core/schema/JanusGraphManagement.html#getRelationTypes-java.lang.Class-)

**Comment by robertdale** [comment]
If you're trying to figure out how to inspect your schema/indexes, see this script https://gist.github.com/robertdale/ad4c63910009dd1118abe67b33ce41e1

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
