### ISSUE TITLE
Support HBase 2.0

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#915]
HBase 2.0 beta is available now.
https://lists.apache.org/thread.html/a6af33e5bd79c80535bd94e1161bdf4a3424abe2cba222c99396383d@%3Cannounce.apache.org%3E

There are two approaches to support it.

1. Upgrade the JanusGraph bundled HBase version to HBase 2.0.
We have to consider compatibility with HBase 1.x installations. Mainly JanusGraph bundled with HBase 2.0 can work well with HBase 1.x server.

2. Keep the bundled HBase version at 1.x.  Test and claim support for the following:
  JanusGraph bundled with HBase 1.x can work with HBase 2.0 server.
  JanusGraph bundled with HBase 2.0 can work with HBase 2.0 server.

**Comment by jerryjch** [comment]
https://s.apache.org/hbase-2.0.0-ANNOUNCE

**Comment by jerryjch** [comment]
@pluradj  Yes.

**Comment by sarathkumarsubramanian** [comment]
Can we expect support for HBase 2.0 in upcoming JanusGraph 0.3.0 ?

**Comment by pluradj** [comment]
@sarathkumarsubramanian follow on the [janusgraph-dev](https://groups.google.com/d/msg/janusgraph-dev/0ng5lHio4TQ/1F_BeHP2AQAJ) thread

**Comment by jerryjch** [comment]
Some update here.
See what I outlined in #1047.  They will apply here as well.
Additionally, hbase-shaded-server is no longer available in HBase 2.0.  Instead, it has hbase-shaded-mapreduce, which will be used by janusgraph-hadoop to get hbase input formats.

**Comment by jerryjch** [comment]
JanusGraph 0.3.0 has been released.  I plan to do the following plan for HBase 2.x
 - [ ]  In JanusGraph 0.3.1, we will claim support for HBase 2.0 and 2.1 after testing, but we will keep the bundled version at hbase 1, and will not upgrade the bundled version to hbase 2.  The reason is that hbase 2 client will not work with HBase 1.x server. We want to maintain compatibility for the moment.
 - [ ]  But in 0.3.1, we will create a maven profile for hbase 2, with all the testing, default off.
 - [ ]  In the next JanusGraph major release (say 0.4), we will make the hbase 2 profile as default build with bundled HBase version 2.

I will create some sub-issues for the above.

**Comment by ardenliu** [comment]
does JanusGraph 0.3.1 support HBase 2.1.x?

**Comment by jerryjch** [comment]
@ardenliu Please see the above comments. Thanks.

**Comment by jerryjch** [comment]
@ardenliu We don't claim support yet in 0.3.1 officially.  But see my update in the above comment.

**Comment by samyElaiassi** [comment]
what specific action need to be done in order to run on top of hbase 2.0.x ? 
I'm struggling to find how to test it

**Comment by FlorianHockmann** [comment]
@jerryjch Are you planning to come back to this for 0.4.0? I think we could be able to target a release date somewhere end of this month and this seems to be the last bigger issue that is still open.

**Comment by jerryjch** [comment]
@FlorianHockmann Thanks for pinging. I have recently changed work place, and am no longer covered by CCLA. I am trying to get a new CCLA.

**Comment by sushil-singh-guavus** [comment]
Hi I have tried to build source code using mvn clean install -Phbase2 -DskipTests , but it is giving DependencyConvergency errors due to failed rules. I think profiling is not working properly, Can any body help. I am using hbase2 version as 2.0.2.

Dependency convergence error for org.apache.hbase:hbase-shaded-client:2.0.2 paths to dependency are:
+-org.janusgraph:janusgraph-dist-hadoop-2:0.4.0-SNAPSHOT
  +-org.apache.hbase:hbase-shaded-client:2.0.2
and
+-org.janusgraph:janusgraph-dist-hadoop-2:0.4.0-SNAPSHOT
  +-org.janusgraph:janusgraph-all:0.4.0-SNAPSHOT
    +-org.apache.hbase:hbase-shaded-client:1.2.6

**Comment by FlorianHockmann** [comment]
@jerryjch I just started a discussion thread for the 0.4.0 release and this is the biggest issue still open which currently has the 0.4.0 milestone:
https://groups.google.com/forum/#!topic/janusgraph-dev/myWnQEhNTPk
I suggest that we move this to the 0.4.x milestone so it doesn't delay the release. Please comment on that thread if you disagree, especially if you are already working on this.
(I'm just linking the thread here so you don't miss it.)

**Comment by jerryjch** [comment]
@FlorianHockmann Let's move this out of 0.4.0.

**Comment by jerryjch** [comment]
@sushil-singh-guavus Can you take a look at this commit:
https://github.com/jerryjch/janusgraph/commit/bc3a3947f4b2a8ab2a10167bc1487e0d6d411531
particularly the .travis.yml file?

**Comment by sushil-singh-guavus** [comment]
@jerryjch thnx for the info

I build the source code with default hbase2 profile with version 2.1.0 using  mvn clean install -Phbase2 -Pjanusgraph-release -Dhbase.profile -Dgpg.skip=true -DskipTests=true. it worked

But with hbase 2.0.2 , i was getting Dependency converge errors, So as of now we are trying if version 2.1.0 works with our platform then no issues, otherwise what should be the solution from community side ?

<img width="1440" alt="Screenshot 2019-06-10 at 12 26 46 PM" src="https://user-images.githubusercontent.com/49549767/59610164-7218cc00-9136-11e9-8e05-e972d0b6f82f.png">

**Comment by jerryjch** [comment]
I created a PR to address the last remaining task of the issue PR #1637.

**Comment by jerryjch** [comment]
The last part of the issue is done:
 - [x]  In the next JanusGraph major release (say 0.4), we will make the hbase 2 profile as default build with bundled HBase version 2.
