### ISSUE TITLE
JanusGraph v0.2.0 not working on MacOS Sierra

### ISSUE THREAD

**Issue by bahtiyarerden** [JanusGraph/janusgraph#954]
Hello i am trying to start janusgraph on MacOS Sierra but i am getting this timeout exceed exception.

MacBook-Pro:bin dev$ ./janusgraph.sh start
Forking Cassandra...
Running `nodetool statusthrift`............. timeout exceeded (60 seconds)
See /Users/dev/Desktop/Tez/tez-execution/janusgraph-0.2.0-hadoop2/bin/../log/cassandra.log for Cassandra log output.

How can i handle this issue? Thanks

**Comment by pluradj** [comment]
Do you see any `WARN` or `ERROR` messages in the `cassandra.log`?

**Comment by bahtiyarerden** [comment]
I found the problem. Cassandra is not working properly with Java 9. So i downgraded Java version to 8 and now it is working.

I commented out the 'ThreadPriorityPolicy=42' line from the cassandra config file to overcome this problem. But I think it is not solution.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
