### ISSUE TITLE
No /conf file?

### ISSUE THREAD

**Issue by havenwang** [JanusGraph/janusgraph#996]
From the documentation I see a reference to a `./conf` file in the JanusGraph project, but this appears to be missing.

For example I see from `http://docs.janusgraph.org/latest/configuration.html#_janusgraph_server`:
```
"Configuring JanusGraph Server is accomplished through a JanusGraph Server yaml configuration file located in the ./conf/gremlin-server directory in the JanusGraph distribution."
```

**Comment by robertdale** [comment]
What version doesn't have this?

```
[~]$ cd janusgraph-0.2.0-hadoop2/
[janusgraph-0.2.0-hadoop2]$ ll ./conf/gremlin-server 
total 32K
-rw-rw-r--. 1 rdale rdale 2.3K 2017-10-11 20:36 gremlin-server-berkeleyje.yaml
-rw-rw-r--. 1 rdale rdale 2.4K 2017-10-11 20:36 gremlin-server-configuration.yaml
-rw-rw-r--. 1 rdale rdale 2.4K 2018-04-06 12:45 gremlin-server.yaml
-rw-rw-r--. 1 rdale rdale  437 2017-10-11 20:36 janusgraph-berkeleyje-es-server.properties
-rw-rw-r--. 1 rdale rdale  109 2017-10-11 20:36 janusgraph-berkeleyje-server.properties
-rw-rw-r--. 1 rdale rdale 5.4K 2017-10-11 20:36 janusgraph-cassandra-es-server.properties
-rw-rw-r--. 1 rdale rdale  668 2017-10-11 20:36 log4j-server.properties
```

**Comment by chupman** [comment]
@havenwang You need to download a [release](https://github.com/JanusGraph/janusgraph/releases/), unzip and change directories to (most likely)janusgraph-0.2.0-hadoop2. The source code from github has to be [built](http://docs.janusgraph.org/latest/building.html) before it can be used.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
